import type { Meta, StoryObj } from "@storybook/web-components-vite";
import "../src/index";
import { renderCard } from "../storybook/render-card";
import type { EntityDefinition } from "../storybook/mock-hass";

interface Args { cardType:string; config:Record<string,unknown>; entities:Record<string,EntityDefinition>; width:number }
const meta:Meta<Args>={
  title:"Cards/Complete catalogue",
  args:{cardType:"custom:luma-heading-card",config:{heading:"Luma component"},entities:{},width:720},
  render:(args)=>renderCard(args.cardType,args.config,args.entities,args.width),
  parameters:{controls:{disable:true}},
};
export default meta;
type Story=StoryObj<Args>;
const story=(cardType:string,config:Record<string,unknown>,entities:Record<string,EntityDefinition>={},width=720):Story=>({args:{cardType,config,entities,width}});
const e=(state:string|number,unit?:string,attributes:Record<string,unknown>={}):EntityDefinition=>({state,attributes:{unit_of_measurement:unit,...attributes}});

export const Action=story("custom:luma-action-card",{name:"Evening scene",subtitle:"Living room · warm lights",icon:"mdi:weather-sunset",color:"#e6a11b",tap_action:{action:"perform-action",perform_action:"scene.turn_on",target:{entity_id:"scene.evening"}},show_arrow:true});
export const ActiveEntities=story("custom:luma-active-card",{name:"Currently active",active:{include:[{domain:"light"},{domain:"media_player",state:["playing"]}]}},{"light.sofa":{...e("on"),area:"Living room"},"light.kitchen":{...e("off"),area:"Kitchen"},"media_player.tv":{...e("playing",undefined,{media_title:"Planet Earth"}),area:"Living room"}});
export const Alarm=story("custom:luma-alarm-card",{entity:"alarm_control_panel.home",name:"Home security",modes:[{mode:"away",name:"Away"},{mode:"night",name:"Night"},{mode:"disarm",name:"Disarm"}]},{"alarm_control_panel.home":e("armed_night")});
export const BatteryHero=story("custom:luma-battery-hero-card",{title:"Batteries",subtitle:"Devices below 60%",maximum:60},{"sensor.door_battery":{...e(18,"%"),device:"Front door"},"sensor.remote_battery":{...e(47,"%"),device:"TV remote"},"sensor.phone_battery":{...e(91,"%"),device:"Phone"}},900);
export const BatteryGrid=story("custom:luma-battery-grid-card",{name:"Needs attention",description:"Sorted by remaining charge",minimum:0,maximum:60},{"sensor.door_battery":{...e(18,"%"),device:"Front door"},"sensor.remote_battery":{...e(47,"%"),device:"TV remote"}});
export const CameraActivity=story("custom:luma-camera-activity-card",{name:"Recent activity",cameras:[{name:"Driveway",camera_entity:"camera.driveway",timeline_entity:"sensor.driveway_timeline"},{name:"Garden",camera_entity:"camera.garden",timeline_entity:"sensor.garden_timeline"}]},{"sensor.driveway_timeline":e("2",undefined,{events:[{type:"vehicle",timestamp:new Date(Date.now()-420000).toISOString(),snapshot:"https://picsum.photos/seed/luma-camera/900/500",url:""}]}),"sensor.garden_timeline":e("0",undefined,{events:[]})},900);
export const Climate=story("custom:luma-climate-card",{entity:"climate.living_room",name:"Living room climate",modes:[{mode:"off",name:"Off"},{mode:"heat",name:"Heat"},{mode:"cool",name:"Cool"}]},{"climate.living_room":e("heat",undefined,{current_temperature:22.4,temperature:23,hvac_modes:["off","heat","cool"]})});
export const Comfort=story("custom:luma-comfort-card",{name:"Indoor comfort",temperature_entity:"sensor.indoor_temperature",humidity_entity:"sensor.indoor_humidity",pm25_entity:"sensor.pm25",outdoor_temperature_entity:"sensor.outdoor_temperature"},{"sensor.indoor_temperature":e(22.7,"°C"),"sensor.indoor_humidity":e(44,"%"),"sensor.pm25":e(9,"µg/m³"),"sensor.outdoor_temperature":e(17.2,"°C")});
export const ControlGroup=story("custom:luma-control-group-card",{items:[{entity:"light.ceiling",name:"Ceiling",icon:"mdi:ceiling-light"},{entity:"light.sofa",name:"Sofa",icon:"mdi:floor-lamp"},{entity:"switch.fan",name:"Fan",icon:"mdi:fan"}]},{"light.ceiling":e("on"),"light.sofa":e("off"),"switch.fan":e("on")});
export const Disclosure=story("custom:luma-disclosure-card",{name:"Advanced controls",icon:"mdi:tune-variant",summary:"Three optional controls",open:true,cards:[{type:"custom:luma-control-card",entity:"switch.boost",name:"Boost",tap_action:{action:"toggle"}},{type:"custom:luma-metric-card",entity:"sensor.runtime",name:"Runtime"}]},{"switch.boost":e("off"),"sensor.runtime":e(34,"min")});
export const Discovery=story("custom:luma-discovery-card",{mode:"favorites",limit:5,empty_text:"No matching entities"},{"light.sofa":{...e("on"),labels:["favorite"],area:"Living room"},"switch.garden":{...e("off"),labels:["favorite"],area:"Garden"}});
export const EnergyFlow=story("custom:luma-energy-flow-card",{solar_entity:"sensor.solar_power",grid_entity:"sensor.grid_power",tap_action:{action:"navigate",navigation_path:"/energy"}},{"sensor.solar_power":e(4380,"W"),"sensor.grid_power":e(1240,"W")},900);
export const EntityGrid=story("custom:luma-entity-grid-card",{domain:"sensor",entity_pattern:"sensor.service_*",columns:3,tablet_columns:2,mobile_columns:1,icon:"mdi:server-network",state_map:{up:"Available",down:"Offline"}},{"sensor.service_api":{...e("up"),platform:"uptime_kuma"},"sensor.service_storage":{...e("up"),platform:"uptime_kuma"},"sensor.service_gateway":{...e("down"),platform:"uptime_kuma"}},900);
export const Heading=story("custom:luma-heading-card",{heading:"Comfort",description:"Temperature, humidity and air quality",icon:"mdi:home-thermometer-outline",tap_action:{action:"navigate",navigation_path:"/rooms"}});
export const Gate=story("custom:luma-gate-card",{entity:"cover.driveway_gate",state_entity:"binary_sensor.driveway_gate",pedestrian_entity:"button.pedestrian_gate",name:"Driveway gate",kind:"cover",display:"full"},{"cover.driveway_gate":e("closed"),"binary_sensor.driveway_gate":e("off"),"button.pedestrian_gate":e("unknown")});
export const History=story("custom:luma-history-card",{title:"Energy today",hours_to_show:18,unit:"kW",decimals:1,series:[{entity:"sensor.solar_power",name:"Solar",color:"#e6a11b"},{entity:"sensor.home_power",name:"Home",color:"#6574c4"}]},{"sensor.solar_power":e(4.2,"kW"),"sensor.home_power":e(2.7,"kW")},900);
export const HomelabHero=story("custom:luma-homelab-hero-card",{name:"Home lab",icon:"mdi:server-network",tap_action:{action:"navigate",navigation_path:"/homelab"}},{"binary_sensor.api":{...e("on"),labels:["infrastructure"]},"update.hypervisor":{...e("on"),labels:["infrastructure_update"]}},900);
export const Iframe=story("custom:luma-iframe-card",{url:"https://www.openstreetmap.org/export/embed.html?bbox=19.0%2C47.4%2C19.2%2C47.6",height:300,title:"Garden map"},{},900);
export const IrrigationHero=story("custom:luma-irrigation-hero-card",{controller_entity:"binary_sensor.irrigation_controller",rain_entity:"binary_sensor.rain",suspended_entity:"switch.irrigation_suspended",program_entity:"sensor.irrigation_state",zones:["switch.front_lawn","switch.drip"],active_program_entity:"sensor.active_program",progress_entity:"sensor.irrigation_progress",remaining_entity:"sensor.irrigation_remaining"},{"binary_sensor.irrigation_controller":e("on"),"binary_sensor.rain":e("off"),"switch.irrigation_suspended":e("off"),"switch.front_lawn":e("on",undefined,{friendly_name:"Front lawn"}),"switch.drip":e("off",undefined,{friendly_name:"Drip line"}),"sensor.irrigation_state":e("Running"),"sensor.active_program":e("Morning lawn"),"sensor.irrigation_progress":e(46,"%"),"sensor.irrigation_remaining":e(18,"min")},900);
export const IrrigationProgram=story("custom:luma-irrigation-program-card",{name:"Morning lawn",button_entity:"button.start_morning",active_program_entity:"sensor.active_program",program_name:"Morning lawn",progress_entity:"sensor.irrigation_progress",state_entity:"sensor.irrigation_state",soak_remaining_entity:"sensor.irrigation_soak_remaining",runtime:"42 minutes"},{"button.start_morning":e("unknown"),"sensor.active_program":e("Morning lawn"),"sensor.irrigation_progress":e(46,"%"),"sensor.irrigation_state":e("Lawn soaking"),"sensor.irrigation_soak_remaining":e(720,"s")});
export const IrrigationSchedule=story("custom:luma-irrigation-schedule-card",{name:"Weekday schedule",enabled_entity:"input_boolean.schedule",start_entity:"input_datetime.start",day_entities:["input_boolean.mon","input_boolean.tue","input_boolean.wed","input_boolean.thu","input_boolean.fri","input_boolean.sat","input_boolean.sun"]},{"input_boolean.schedule":e("on"),"input_datetime.start":e("05:30:00"),"input_boolean.mon":e("on"),"input_boolean.tue":e("off"),"input_boolean.wed":e("on"),"input_boolean.thu":e("off"),"input_boolean.fri":e("on"),"input_boolean.sat":e("off"),"input_boolean.sun":e("off")});
export const IrrigationZone=story("custom:luma-irrigation-zone-card",{entity:"switch.front_lawn",name:"Front lawn",duration_entity:"number.adhoc_minutes",default_duration:12,progress_entity:"sensor.zone_progress",remaining_entity:"sensor.zone_remaining"},{"switch.front_lawn":e("on"),"number.adhoc_minutes":e(12,"min",{min:1,max:90,step:1}),"sensor.zone_progress":e(63,"%"),"sensor.zone_remaining":e("4:26")});
export const LawnHero=story("custom:luma-lawn-hero-card",{mower:"vacuum.mower",battery:"sensor.mower_battery",progress:"sensor.mower_progress",title:"Garden mower",subtitle:"North lawn"},{"vacuum.mower":e("mowing"),"sensor.mower_battery":e(73,"%"),"sensor.mower_progress":e(38,"%")},900);
export const LawnControl=story("custom:luma-lawn-control-card",{mower:"vacuum.mower",progress:"sensor.mower_progress",location:"sensor.mower_location",time_left:"sensor.mower_remaining",start_action:{action:"perform-action",perform_action:"vacuum.start"},stop_action:{action:"perform-action",perform_action:"vacuum.return_to_base"}},{"vacuum.mower":e("mowing"),"sensor.mower_progress":e(38,"%"),"sensor.mower_location":e("North lawn"),"sensor.mower_remaining":e("47 min")});
export const Layout=story("custom:luma-layout-card",{columns:2,tablet_columns:2,mobile_columns:1,cards:[{type:"custom:luma-metric-card",entity:"sensor.temperature",name:"Temperature"},{type:"custom:luma-control-card",entity:"light.desk",name:"Desk light",tap_action:{action:"toggle"}}]},{"sensor.temperature":e(22.4,"°C"),"light.desk":e("on")},900);
export const Logbook=story("custom:luma-logbook-card",{entities:["switch.front_lawn","sensor.irrigation_state"],title:"Irrigation history",hours_to_show:24,max_items:8,collapse:5},{"switch.front_lawn":e("off"),"sensor.irrigation_state":e("Ready")});
export const Navigation=story("custom:luma-navigation-card",{name:"Solar production",subtitle:"Forecast and daily history",icon:"mdi:solar-power",color:"#e6a11b",tap_action:{action:"navigate",navigation_path:"/energy/solar"}});
export const Navbar=story("custom:luma-navbar-card",{routes:[{label:"Home",icon:"mdi:home-outline",url:"/home"},{label:"Rooms",icon:"mdi:floor-plan",url:"/rooms"},{label:"Energy",icon:"mdi:lightning-bolt-outline",url:"/energy"},{label:"Settings",icon:"mdi:cog-outline",url:"/config"}]},{},900);
export const Popup=story("custom:luma-popup-card",{hash:"demo",name:"Quick controls",subtitle:"Material 3 inspired bottom sheet",icon:"mdi:tune-variant",cards:[{type:"custom:luma-control-card",entity:"light.sofa",name:"Sofa light",tap_action:{action:"toggle"}},{type:"custom:luma-climate-card",entity:"climate.living_room",name:"Climate"}]},{"light.sofa":e("on"),"climate.living_room":e("cool",undefined,{current_temperature:23.1,temperature:22})});
export const RackCooling=story("custom:luma-rack-cooling-card",{intake_entity:"sensor.rack_intake",exhaust_entity:"sensor.rack_exhaust",delta_entity:"sensor.rack_delta",rpm_entity:"sensor.fan_1",rpm_2_entity:"sensor.fan_2",pwm_entity:"sensor.fan_speed",failure_entity:"binary_sensor.fan_failure"},{"sensor.rack_intake":e(24.1,"°C"),"sensor.rack_exhaust":e(30.8,"°C"),"sensor.rack_delta":e(6.7,"°C"),"sensor.fan_1":e(1160,"rpm"),"sensor.fan_2":e(1090,"rpm"),"sensor.fan_speed":e(42,"%"),"binary_sensor.fan_failure":e("off")},900);
export const Remote=story("custom:luma-remote-card",{remote_entity:"remote.tv",media_entity:"media_player.tv",name:"Living room TV",artwork:true,apps:[{name:"YouTube",activity:"com.google.android.youtube.tv"},{name:"Netflix",activity:"com.netflix.ninja"}]},{"remote.tv":e("on"),"media_player.tv":e("playing",undefined,{media_title:"Planet Earth",app_name:"Netflix",entity_picture:"https://picsum.photos/seed/luma-tv/500/500"})});
export const Room=story("custom:luma-room-card",{name:"Living room",icon:"mdi:sofa-outline",path:"/rooms/living-room",subtitle:"Relax and entertainment",temperature_entity:"sensor.living_temperature",humidity_entity:"sensor.living_humidity",light_entity:"light.living_room",cover_entity:"cover.living_room",items:[{entity:"media_player.tv",icon:"mdi:television"}]},{"sensor.living_temperature":e(22.6,"°C"),"sensor.living_humidity":e(43,"%"),"light.living_room":e("on"),"cover.living_room":e("open"),"media_player.tv":e("off")});
export const SensorGrid=story("custom:luma-sensor-grid-card",{name:"Environment",icon:"mdi:chart-box-outline",columns:3,surface:true,items:[{entity:"sensor.temperature",name:"Temperature"},{entity:"sensor.humidity",name:"Humidity"},{entity:"sensor.co2",name:"CO₂"}]},{"sensor.temperature":e(22.4,"°C"),"sensor.humidity":e(46,"%"),"sensor.co2":e(612,"ppm")},900);
export const Tabs=story("custom:luma-tab-card",{tabs:[{name:"Summary",icon:"mdi:view-dashboard-outline",cards:[{type:"custom:luma-metric-card",entity:"sensor.temperature",name:"Temperature"}]},{name:"Controls",icon:"mdi:tune-variant",cards:[{type:"custom:luma-control-card",entity:"light.sofa",name:"Sofa light",tap_action:{action:"toggle"}}]}]},{"sensor.temperature":e(22.4,"°C"),"light.sofa":e("on")});
export const Temperature=story("custom:luma-temperature-card",{name:"Home temperatures",primary_entity:"sensor.home_average",items:[{entity:"sensor.living_temperature",name:"Living room"},{entity:"sensor.bedroom_temperature",name:"Bedroom"},{entity:"sensor.office_temperature",name:"Office"}]},{"sensor.home_average":e(22.3,"°C"),"sensor.living_temperature":e(22.8,"°C"),"sensor.bedroom_temperature":e(21.5,"°C"),"sensor.office_temperature":e(22.6,"°C")});
export const Timeline=story("custom:luma-timeline-card",{entity:"sensor.security_timeline",title:"Security timeline",limit:6},{"sensor.security_timeline":e("3",undefined,{events:[{type:"person",timestamp:new Date(Date.now()-480000).toISOString(),camera:"Front door",thumbnail:"https://picsum.photos/seed/luma-event/640/360"}]})},900);
export const Update=story("custom:luma-update-card",{entity:"update.home_assistant",name:"Home Assistant",icon:"mdi:home-assistant"},{"update.home_assistant":e("on",undefined,{installed_version:"2026.8.1",latest_version:"2026.8.3",in_progress:false})});
export const WasteAcknowledgement=story("custom:luma-waste-ack-card",{entity:"input_boolean.waste_ready",confirmation:"Mark the bins as prepared?",color:"#e6a11b"},{"input_boolean.waste_ready":e("off")});
export const WasteCollection=story("custom:luma-waste-collection-card",{entity:"sensor.plastic_collection",name:"Plastic",icon:"mdi:recycle",color:"#e6c51b"},{"sensor.plastic_collection":e("2026-08-25",undefined,{daysTo:2})});
export const WasteHero=story("custom:luma-waste-hero-card",{title:"Waste collection",acknowledgement_entity:"input_boolean.waste_ready",items:[{entity:"sensor.general_collection",name:"General",icon:"mdi:trash-can-outline"},{entity:"sensor.plastic_collection",name:"Plastic",icon:"mdi:recycle",color:"#e6c51b"}]},{"input_boolean.waste_ready":e("off"),"sensor.general_collection":e("2026-08-25",undefined,{daysTo:2}),"sensor.plastic_collection":e("2026-08-25",undefined,{daysTo:2})},900);
export const WeatherForecast=story("custom:luma-weather-forecast-card",{weather_entity:"weather.home",days:7,locale:"en"},{"weather.home":e("partlycloudy",undefined,{temperature:23.5,wind_speed:12,humidity:44})},980);
export const WeatherHero=story("custom:luma-weather-hero-card",{weather_entity:"weather.home",temperature_entity:"sensor.outdoor_temperature",humidity_entity:"sensor.outdoor_humidity",name:"Weather",back_path:"/home"},{"weather.home":e("partlycloudy",undefined,{temperature:23.5,wind_speed:12,humidity:44}),"sensor.outdoor_temperature":e(23.5,"°C"),"sensor.outdoor_humidity":e(44,"%")},900);
