import type { Meta, StoryObj } from '@storybook/web-components-vite';
import '../src/index';
import { renderCard } from '../storybook/render-card';
import type { EntityDefinition } from '../storybook/mock-hass';
interface Args {config:Record<string,unknown>;entities:Record<string,EntityDefinition>;width:number}
const meta:Meta<Args>={title:'Patterns/Infrastructure',args:{width:1100},render:a=>renderCard(String(a.config.type),a.config,a.entities,a.width),parameters:{controls:{disable:true}}};
export default meta;
type Story=StoryObj<Args>;
export const VirtualMachines:Story={args:{config:{type:'custom:luma-entity-grid-card',entity_pattern:'binary_sensor.vm_*',columns:3,tablet_columns:2,mobile_columns:1,name_remove:[' status'],state_map:{on:'Running',off:'Stopped'},extra_cards:[{type:'custom:luma-control-card',entity:'switch.workstation',name:'Workstation',subtitle:'Confirmed power control',tap_action:{action:'toggle',confirmation:{text:'Change virtual machine power state?'}}}]},entities:{'binary_sensor.vm_home':{state:'on',attributes:{friendly_name:'Home Automation status'}},'binary_sensor.vm_docker':{state:'on',attributes:{friendly_name:'Applications status'}},'switch.workstation':{state:'off',attributes:{friendly_name:'Workstation'}}}}};
export const Updates:Story={args:{config:{type:'custom:luma-discovery-card',mode:'infrastructure-updates',label:'infra_update',columns:3,tablet_columns:2,mobile_columns:1},entities:{'update.alpha':{state:'on',labels:['infra_update'],attributes:{friendly_name:'Gateway',installed_version:'1.0',latest_version:'1.1',supported_features:1}},'update.beta':{state:'on',labels:['infra_update'],attributes:{friendly_name:'Storage server',installed_version:'7.1',latest_version:'7.2',in_progress:40,supported_features:1}},'update.gamma':{state:'off',labels:['infra_update'],attributes:{friendly_name:'Starting update',in_progress:0,supported_features:1}}}}};
export const ComputeMetrics:Story={args:{config:{type:'custom:luma-layout-card',columns:3,tablet_columns:2,mobile_columns:2,cards:[{type:'custom:luma-metric-card',entity:'sensor.cpu',name:'CPU',decimals:1,secondary_entity:'sensor.cpu_temperature',secondary_prefix:'Temperature: ',secondary_decimals:0,secondary_tap_action:{action:'more-info',entity:'sensor.cpu_temperature'},tap_action:{action:'more-info'}},{type:'custom:luma-metric-card',entity:'sensor.memory',name:'Memory',decimals:1},{type:'custom:luma-metric-card',entity:'sensor.rx',name:'Network RX',decimals:2,secondary_entity:'sensor.tx',secondary_prefix:'TX: ',secondary_decimals:2,secondary_tap_action:{action:'more-info',entity:'sensor.tx'},tap_action:{action:'more-info'}}]},entities:{'sensor.cpu':{state:12.2,attributes:{unit_of_measurement:'%'}},'sensor.cpu_temperature':{state:54,attributes:{unit_of_measurement:'°C'}},'sensor.memory':{state:48.5,attributes:{unit_of_measurement:'%'}},'sensor.rx':{state:4.2,attributes:{unit_of_measurement:'MB/s'}},'sensor.tx':{state:1.8,attributes:{unit_of_measurement:'MB/s'}}}}};
