import { LitElement, css, html, nothing, type PropertyValues } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { runAction } from "../helpers";
import { lumaTokens } from "../styles";
import type { HomeAssistant, LovelaceCard, LumaAction } from "../types";

interface HeroConfig{type:string;mower:string;battery?:string;progress?:string;title?:string;subtitle?:string;icon?:string;top_spacing?:number;tap_action?:LumaAction}
interface ControlConfig{type:string;mower:string;progress?:string;location?:string;elapsed?:string;time_left?:string;start_action:LumaAction;stop_action:LumaAction}
const labels:Record<string,string>={docked:"Dokkolva",mowing:"Nyírás folyamatban",paused:"Szünetel",returning:"Visszatér a dokkolóhoz",error:"Figyelmet igényel",unavailable:"Nem elérhető",unknown:"Ismeretlen"};
const toneFor=(s:string)=>s==="mowing"?"var(--success-color)":s==="paused"||s==="returning"?"var(--warning-color)":s==="error"||s==="unavailable"?"var(--error-color)":"var(--primary-color)";

@customElement("luma-lawn-hero-card")
export class LumaLawnHeroCard extends LitElement implements LovelaceCard{
 @property({attribute:false})hass?:HomeAssistant;@state()private config?:HeroConfig;
 static styles=[lumaTokens,css`
  ha-card{position:relative;min-height:150px;padding:27px;border:1px solid color-mix(in srgb,var(--tone) 20%,transparent);border-radius:var(--luma-radius-hero);background:radial-gradient(circle at 90% 18%,color-mix(in srgb,var(--tone) 19%,transparent),transparent 31%),linear-gradient(135deg,color-mix(in srgb,var(--tone) 14%,var(--luma-surface)),var(--luma-surface) 66%);box-shadow:0 18px 50px rgba(0,0,0,.075);overflow:hidden}.top{display:grid;grid-template-columns:58px minmax(0,1fr) auto;grid-template-areas:"icon title badge" "icon sub badge";align-items:center;gap:4px 17px}.icon{grid-area:icon;display:grid;place-items:center;width:58px;height:58px;border-radius:19px;color:var(--tone);background:color-mix(in srgb,var(--tone) 16%,transparent)}.icon ha-icon{--mdc-icon-size:31px}.title{grid-area:title;align-self:end;font-size:clamp(21px,4vw,27px);line-height:1.1;font-weight:var(--luma-weight-title)}.sub{grid-area:sub;align-self:start;color:var(--luma-muted);font-size:12px}.badge{grid-area:badge;display:inline-flex;align-items:center;gap:7px;padding:7px 11px;border-radius:999px;color:var(--tone);background:color-mix(in srgb,var(--tone) 13%,transparent);font-size:11px;font-weight:720}.badge ha-icon{--mdc-icon-size:15px}.stats{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.stat{display:flex;align-items:center;gap:7px;padding:7px 10px;border-radius:999px;color:var(--luma-muted);background:color-mix(in srgb,var(--primary-text-color) 5%,transparent);font-size:11px;font-weight:650}.stat ha-icon{--mdc-icon-size:16px;color:var(--tone)}@media(max-width:599px){ha-card{min-height:0;padding:19px}.top{grid-template-columns:46px minmax(0,1fr);grid-template-areas:"icon title" "icon sub";gap:3px 12px}.icon{width:46px;height:46px;border-radius:15px}.icon ha-icon{--mdc-icon-size:25px}.badge{display:none}.stats{margin-top:14px}.stat{flex:1 1 auto;justify-content:center}}
 `];
 setConfig(c:HeroConfig){if(!c?.mower)throw Error("Lawn hero requires mower.");this.config={title:"Yuka Mini 2",icon:"mdi:robot-mower",...c}}getCardSize(){return 3}
 protected shouldUpdate(changed:PropertyValues<this>){if(!changed.has("hass"))return true;const old=changed.get("hass")as HomeAssistant|undefined;return!old||[this.config?.mower,this.config?.battery,this.config?.progress].filter(Boolean).some(id=>old.states[id!]!==this.hass?.states[id!])}
 render(){if(!this.hass||!this.config)return nothing;const s=this.hass.states[this.config.mower]?.state||"unknown",tone=toneFor(s),battery=this.config.battery?this.hass.states[this.config.battery]?.state:undefined,progress=this.config.progress?this.hass.states[this.config.progress]?.state:undefined,active=["mowing","paused","returning"].includes(s),subtitle=this.config.subtitle||(active&&progress!==undefined?`${labels[s]||s} · ${Math.round(Number(progress)||0)}% kész`:labels[s]||s);return html`<ha-card class=${this.config.tap_action?"interactive":""} style=${`--tone:${tone};margin-top:${this.config.top_spacing||0}px`} @click=${()=>runAction(this,this.hass!,this.config?.tap_action,this.config?.mower)}><div class="top"><span class="icon"><ha-icon icon=${this.config.icon}></ha-icon></span><span class="title">${this.config.title}</span><span class="sub">${subtitle}</span><span class="badge"><ha-icon icon=${active?"mdi:motion-play-outline":s==="docked"?"mdi:home-battery-outline":"mdi:alert-circle-outline"}></ha-icon>${labels[s]||s}</span></div><div class="stats">${battery!==undefined?html`<span class="stat"><ha-icon icon="mdi:battery-high"></ha-icon>${battery}% akkumulátor</span>`:nothing}${progress!==undefined&&active?html`<span class="stat"><ha-icon icon="mdi:progress-clock"></ha-icon>${Math.round(Number(progress)||0)}% kész</span>`:nothing}<span class="stat"><ha-icon icon="mdi:map-marker-radius-outline"></ha-icon>Yuka rendszer</span></div></ha-card>`}
}

@customElement("luma-lawn-control-card")
export class LumaLawnControlCard extends LitElement implements LovelaceCard{
 @property({attribute:false})hass?:HomeAssistant;@state()private config?:ControlConfig;@state()private pending?:"start"|"stop";private timer?:number;
 static styles=[lumaTokens,css`
  ha-card{padding:18px;border:1px solid color-mix(in srgb,var(--tone) 15%,transparent);border-radius:var(--luma-radius-card);background:linear-gradient(145deg,color-mix(in srgb,var(--tone) 8%,var(--luma-surface)),var(--luma-surface) 72%);box-shadow:0 13px 34px color-mix(in srgb,var(--tone) 6%,transparent)}.head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:4px 12px}.name{font-size:15px;font-weight:720}.state{padding:5px 8px;border-radius:999px;color:var(--tone);background:color-mix(in srgb,var(--tone) 12%,transparent);font-size:10px;font-weight:720}.detail{grid-column:1/-1;color:var(--luma-muted);font-size:10px}.progress{height:8px;margin-top:14px;border-radius:999px;background:color-mix(in srgb,var(--primary-text-color) 7%,transparent);overflow:hidden}.fill{height:100%;border-radius:inherit;background:linear-gradient(90deg,color-mix(in srgb,var(--tone) 72%,white),var(--tone));transition:width .35s ease}.actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:15px}.action{display:flex;align-items:center;justify-content:center;gap:7px;min-height:44px;border:1px solid color-mix(in srgb,var(--action-tone) 18%,transparent);border-radius:999px;color:var(--action-tone);background:color-mix(in srgb,var(--action-tone) 11%,transparent);font:inherit;font-size:11px;font-weight:720}.action:disabled{opacity:.42;cursor:default}.action ha-icon{--mdc-icon-size:18px}@media(max-width:420px){ha-card{padding:15px}.actions{gap:7px}.action{min-height:42px;font-size:10px}}
 `];
 setConfig(c:ControlConfig){if(!c?.mower||!c.start_action||!c.stop_action)throw Error("Lawn control requires mower and actions.");this.config=c}getCardSize(){return 3}
 private activate(kind:"start"|"stop"){if(!this.config||!this.hass)return;const s=this.hass.states[this.config.mower]?.state,startDisabled=s==="mowing",stopDisabled=!["mowing","paused","returning"].includes(s);if(kind==="start"?startDisabled:stopDisabled)return;if(this.pending!==kind){this.pending=kind;clearTimeout(this.timer);this.timer=window.setTimeout(()=>this.pending=undefined,3400);return}this.pending=undefined;void runAction(this,this.hass,kind==="start"?this.config.start_action:this.config.stop_action,this.config.mower)}
 render(){if(!this.hass||!this.config)return nothing;const s=this.hass.states[this.config.mower]?.state||"unknown",tone=toneFor(s),active=["mowing","paused","returning"].includes(s),p=Math.max(0,Math.min(100,Number(this.config.progress?this.hass.states[this.config.progress]?.state:0)||0)),loc=this.config.location?this.hass.states[this.config.location]?.state:undefined,elapsed=Number(this.config.elapsed?this.hass.states[this.config.elapsed]?.state:0)||0,left=Number(this.config.time_left?this.hass.states[this.config.time_left]?.state:0)||0,detail=active?`${loc&&!['unknown','unavailable'].includes(loc)?loc:"Aktuális terület"} · ${Math.round(elapsed)} p eltelt · ${Math.round(left)} p hátra`:"A fűnyíró készen áll a következő feladatra";return html`<ha-card style=${`--tone:${tone}`}><div class="head"><span class="name">Aktuális munka</span><span class="state">${labels[s]||s}</span><span class="detail">${detail}</span></div>${active?html`<div class="progress"><div class="fill" style=${`width:${p}%`}></div></div>`:nothing}<div class="actions"><button class="action" style="--action-tone:var(--success-color)" ?disabled=${s==="mowing"} @click=${()=>this.activate("start")}><ha-icon icon=${this.pending==="start"?"mdi:check":s==="paused"?"mdi:play-pause":"mdi:play"}></ha-icon>${this.pending==="start"?"Megerősítés":s==="paused"?"Folytatás":"Indítás"}</button><button class="action" style="--action-tone:var(--error-color)" ?disabled=${!active} @click=${()=>this.activate("stop")}><ha-icon icon=${this.pending==="stop"?"mdi:check":"mdi:stop"}></ha-icon>${this.pending==="stop"?"Megerősítés":"Leállítás"}</button></div></ha-card>`}
}
