import{LitElement,css,html,nothing,type PropertyValues}from"lit";
import{customElement,property,query,state}from"lit/decorators.js";
import{lumaTokens}from"../styles";
import type{HomeAssistant,LovelaceCard}from"../types";
interface Config{type:string;hash:string;name:string;subtitle?:string;icon?:string;cards?:Record<string,unknown>[];max_width?:number}
type ChildCard=HTMLElement&{hass?:HomeAssistant};
@customElement("luma-popup-card")
export class LumaPopupCard extends LitElement implements LovelaceCard{
 @property({attribute:false})hass?:HomeAssistant;@property({type:Boolean})preview=false;@property({type:Boolean})editMode=false;
 @state()private config?:Config;@state()private open=false;@state()private dragY=0;@state()private dragging=false;@query(".content")private content?:HTMLElement;
 private childCards:ChildCard[]=[];private dragStartY=0;private dragStartTime=0;private locationChanged=()=>this.syncLocation();private keyDown=(event:KeyboardEvent)=>{if(this.open&&event.key==="Escape")this.close()};
 static styles=[lumaTokens,css`
 :host{display:block;height:0;min-height:0}.edit-preview{display:grid;grid-template-columns:42px minmax(0,1fr) auto;align-items:center;gap:12px;padding:13px;border:1px dashed color-mix(in srgb,var(--primary-color) 28%,transparent);border-radius:18px;background:color-mix(in srgb,var(--primary-color) 6%,var(--luma-surface))}.preview-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:13px;color:var(--primary-color);background:color-mix(in srgb,var(--primary-color) 13%,transparent)}.preview-icon ha-icon{--mdc-icon-size:22px}.preview-title{font-size:13px;font-weight:720}.preview-meta{margin-top:3px;color:var(--luma-muted);font-size:10px}.preview-open{min-height:34px;padding:7px 11px;border:0;border-radius:999px;color:var(--primary-color);background:color-mix(in srgb,var(--primary-color) 12%,transparent);font:inherit;font-size:10px;font-weight:720}
 .layer{position:fixed;inset:0;z-index:1000;display:grid;align-items:end;justify-items:center;pointer-events:none;visibility:hidden}.layer.open{pointer-events:auto;visibility:visible}.scrim{position:absolute;inset:0;background:rgba(12,13,18,.58);opacity:0;transition:opacity .22s ease}.open .scrim{opacity:calc(1 - var(--drag-progress,0))}.sheet{position:relative;isolation:isolate;display:grid;grid-template-rows:auto minmax(0,1fr);width:min(var(--sheet-width),calc(100vw - 32px));max-height:min(860px,calc(100dvh - 28px));border:1px solid color-mix(in srgb,var(--primary-text-color) 13%,transparent);border-radius:28px 28px 0 0;color:var(--primary-text-color);background:var(--md-sys-color-surface-container-high,var(--primary-background-color,#fafafa));box-shadow:0 -16px 60px rgba(0,0,0,.34);overflow:hidden;transform:translateY(calc(100% + 32px));opacity:.8;transition:transform .32s cubic-bezier(.2,.8,.2,1),opacity .22s ease}.open .sheet{transform:translateY(var(--drag-y,0));opacity:1}.dragging .sheet{transition:none}.handle-zone{position:absolute;z-index:3;top:0;left:0;width:100%;height:28px;cursor:grab;touch-action:none}.dragging .handle-zone{cursor:grabbing}.handle{position:absolute;top:9px;left:50%;width:34px;height:4px;border-radius:99px;background:color-mix(in srgb,var(--primary-text-color) 28%,transparent);transform:translateX(-50%)}header{display:grid;grid-template-columns:42px minmax(0,1fr) 40px;align-items:center;gap:12px;padding:25px 20px 14px;border-bottom:1px solid color-mix(in srgb,var(--primary-text-color) 8%,transparent);background:var(--md-sys-color-surface-container-high,var(--primary-background-color,#fafafa))}.icon{display:grid;place-items:center;width:42px;height:42px;border-radius:14px;color:var(--primary-color);background:color-mix(in srgb,var(--primary-color) 12%,transparent)}.icon ha-icon{--mdc-icon-size:22px}.title{font-size:18px;font-weight:730;line-height:1.15}.subtitle{margin-top:3px;color:var(--luma-muted);font-size:11px}.close{display:grid;place-items:center;width:40px;height:40px;padding:0;border:0;border-radius:50%;color:var(--primary-text-color);background:color-mix(in srgb,var(--primary-text-color) 7%,transparent)}.close ha-icon{--mdc-icon-size:19px}.content{display:grid;align-content:start;gap:14px;min-height:160px;padding:16px 20px calc(22px + env(safe-area-inset-bottom));background:var(--md-sys-color-surface-container-high,var(--primary-background-color,#fafafa));overflow:auto;overscroll-behavior:contain}.loading{display:grid;place-items:center;min-height:160px;color:var(--luma-muted);font-size:12px}@media(min-width:700px){.layer{padding-bottom:18px}.sheet{border-radius:28px;max-height:calc(100dvh - 56px)}}@media(max-width:699px){.sheet{width:100%;max-height:calc(100dvh - 8px);border-right:0;border-bottom:0;border-left:0}.content{padding-right:16px;padding-left:16px}}@media(prefers-reduced-motion:reduce){.scrim,.sheet{transition-duration:.01ms}}`];
 connectedCallback(){super.connectedCallback();window.addEventListener("hashchange",this.locationChanged);window.addEventListener("location-changed",this.locationChanged);window.addEventListener("keydown",this.keyDown);this.syncLocation()}
 disconnectedCallback(){window.removeEventListener("hashchange",this.locationChanged);window.removeEventListener("location-changed",this.locationChanged);window.removeEventListener("keydown",this.keyDown);super.disconnectedCallback()}
 setConfig(c:Config){if(!c?.hash||!c?.name)throw new Error("Luma popup requires hash and name.");this.config={cards:[],max_width:720,...c};this.childCards=[];this.syncLocation()}getCardSize(){return this.isEditing?1:0}
 protected updated(changed:PropertyValues<this>){if(changed.has("config" as never))void this.mountCards();if(changed.has("hass"))for(const card of this.childCards)card.hass=this.hass}
 private get isEditing(){return this.preview||this.editMode||Boolean(this.hass?.editMode)||Boolean(this.closest("hui-card-edit-mode,hui-card-preview"))}
 private syncLocation(){if(!this.config)return;const expected=this.config.hash.startsWith("#")?this.config.hash:"#"+this.config.hash;this.open=window.location.hash===expected}
 private navigate(hash=""){const oldURL=window.location.href;history.pushState(null,"",window.location.pathname+window.location.search+hash);window.dispatchEvent(new Event("location-changed"));window.dispatchEvent(new HashChangeEvent("hashchange",{oldURL,newURL:window.location.href}))}
 private openPreview(){if(this.config)this.navigate(this.config.hash.startsWith("#")?this.config.hash:"#"+this.config.hash)}
 private close(){this.dragY=0;this.dragging=false;this.navigate()}
 private dragStart(event:PointerEvent){this.dragging=true;this.dragStartY=event.clientY;this.dragStartTime=performance.now();(event.currentTarget as HTMLElement).setPointerCapture(event.pointerId)}
 private dragMove(event:PointerEvent){if(this.dragging)this.dragY=Math.max(0,event.clientY-this.dragStartY)}
 private dragEnd(event:PointerEvent){if(!this.dragging)return;const elapsed=Math.max(1,performance.now()-this.dragStartTime),velocity=this.dragY/elapsed;(event.currentTarget as HTMLElement).releasePointerCapture(event.pointerId);this.dragging=false;if(this.dragY>110||velocity>.65)this.close();else this.dragY=0}
 private async mountCards(){if(!this.config||!this.content)return;const helpers=await window.loadCardHelpers?.();if(!helpers)return;this.childCards=(this.config.cards||[]).map(config=>helpers.createCardElement(config)as ChildCard);for(const card of this.childCards){card.hass=this.hass;card.style.width="100%"}this.content.replaceChildren(...this.childCards)}
 render(){if(!this.config)return nothing;return html`${this.isEditing&&!this.open?html`<ha-card class="edit-preview"><span class="preview-icon"><ha-icon icon=${this.config.icon||"mdi:application-brackets-outline"}></ha-icon></span><span><div class="preview-title">${this.config.name}</div><div class="preview-meta">${this.config.hash} · ${this.config.cards?.length||0} tartalmi kártya</div></span><button class="preview-open" @click=${()=>this.openPreview()}>Megnyitás</button></ha-card>`:nothing}<div class=${`layer ${this.open?"open":""} ${this.dragging?"dragging":""}`} style=${`--drag-y:${this.dragY}px;--drag-progress:${Math.min(.75,this.dragY/420)}`} aria-hidden=${!this.open}><div class="scrim" @click=${()=>this.close()}></div><section class="sheet" role="dialog" aria-modal="true" aria-label=${this.config.name} style=${`--sheet-width:${this.config.max_width}px`}><div class="handle-zone" @pointerdown=${this.dragStart} @pointermove=${this.dragMove} @pointerup=${this.dragEnd} @pointercancel=${this.dragEnd}><div class="handle"></div></div><header><span class="icon"><ha-icon icon=${this.config.icon||"mdi:lightning-bolt-outline"}></ha-icon></span><span><div class="title">${this.config.name}</div>${this.config.subtitle?html`<div class="subtitle">${this.config.subtitle}</div>`:nothing}</span><button class="close" aria-label="Bezárás" @click=${()=>this.close()}><ha-icon icon="mdi:close"></ha-icon></button></header><div class="content"><div class="loading">Betöltés…</div></div></section></div>`}
}
