import { LitElement, css, html, nothing } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { localized } from "../localize";
import { lumaTokens } from "../styles";
import type { HomeAssistant, LovelaceCard } from "../types";

interface Config { type:string; weather_entity:string; uv_entity?:string; dewpoint_entity?:string; pressure_trend_entity?:string; wind_direction_entity?:string; wind_gust_entity?:string; rain_1h_entity?:string; rain_6h_entity?:string; rain_24h_entity?:string; observation_entity?:string; sunrise_entity?:string; sunset_entity?:string; air_quality_entity?:string; pollen_entity?:string }
@customElement("luma-weather-details-card")
export class LumaWeatherDetailsCard extends LitElement implements LovelaceCard {
 @property({attribute:false}) hass?:HomeAssistant;@state() private config?:Config;
 static styles=[lumaTokens,css`
  ha-card{padding:15px;border:1px solid var(--luma-border);border-radius:22px;background:linear-gradient(145deg,color-mix(in srgb,var(--primary-color) 7%,var(--luma-surface)),var(--luma-surface) 65%);box-shadow:var(--luma-shadow)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.item{display:grid;grid-template-columns:31px minmax(0,1fr);align-items:center;gap:8px;min-height:48px;padding:8px;border-radius:14px;background:color-mix(in srgb,var(--primary-text-color) 4%,transparent)}.icon{display:grid;place-items:center;width:31px;height:31px;border-radius:10px;color:var(--primary-color);background:color-mix(in srgb,var(--primary-color) 11%,transparent)}ha-icon{--mdc-icon-size:17px}.value{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;font-weight:760}.label{margin-top:2px;color:var(--luma-muted);font-size:8px}.observed{display:flex;align-items:center;gap:6px;margin:11px 3px 0;padding-top:10px;border-top:1px solid var(--luma-border);color:var(--luma-muted);font-size:9px}.observed ha-icon{--mdc-icon-size:13px}@media(max-width:599px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
 `];
 setConfig(c:Config){if(!c?.weather_entity)throw Error("weather_entity required");this.config=c}getCardSize(){return 5}
 private value(id?:string,attr?:string){if(!this.hass)return;return id?this.hass.states[id]?.state:attr?this.hass.states[this.config!.weather_entity]?.attributes?.[attr]:undefined}
 private unit(id?:string,fallback:unknown=""){return String(id?(this.hass?.states[id]?.attributes?.unit_of_measurement||fallback):fallback)}
 private time(id?:string){const raw=this.value(id);if(!raw)return;const d=new Date(String(raw));return Number.isNaN(d.getTime())?raw:d.toLocaleTimeString(this.hass?.locale?.language||"en",{hour:"2-digit",minute:"2-digit"})}
 private item(icon:string,label:string,value:unknown,unit=""){return value==null||value==="unknown"||value==="unavailable"?nothing:html`<div class="item"><span class="icon"><ha-icon icon=${icon}></ha-icon></span><span><div class="value">${value}${unit}</div><div class="label">${label}</div></span></div>`}
 render(){if(!this.hass||!this.config)return nothing;const c=this.config,a=this.hass.states[c.weather_entity]?.attributes||{},observed=this.value(c.observation_entity);return html`<ha-card><div class="grid">${this.item("mdi:weather-sunny-alert","UV-index",this.value(c.uv_entity)??a.uv_index)}${this.item("mdi:water-thermometer",localized(this.hass,"Dew point","Harmatpont"),this.value(c.dewpoint_entity)??a.dew_point,"°")}${this.item("mdi:gauge",localized(this.hass,"Pressure trend","Légnyomástrend"),this.value(c.pressure_trend_entity)??a.pressure, c.pressure_trend_entity?"":` ${a.pressure_unit||"hPa"}`)}${this.item("mdi:compass-outline",localized(this.hass,"Wind direction","Szélirány"),this.value(c.wind_direction_entity)??a.wind_bearing)}${this.item("mdi:weather-tornado",localized(this.hass,"Wind gust","Széllökés"),this.value(c.wind_gust_entity),` ${this.unit(c.wind_gust_entity,a.wind_speed_unit||"km/h")}`)}${this.item("mdi:eye-outline",localized(this.hass,"Visibility","Látótávolság"),a.visibility,` ${a.visibility_unit||"km"}`)}${this.item("mdi:weather-rainy",localized(this.hass,"Rain · 1 hour","Eső · 1 óra"),this.value(c.rain_1h_entity),` ${this.unit(c.rain_1h_entity,"mm")}`)}${this.item("mdi:weather-pouring",localized(this.hass,"Rain · 6 hours","Eső · 6 óra"),this.value(c.rain_6h_entity),` ${this.unit(c.rain_6h_entity,"mm")}`)}${this.item("mdi:weather-pouring",localized(this.hass,"Rain · 24 hours","Eső · 24 óra"),this.value(c.rain_24h_entity),` ${this.unit(c.rain_24h_entity,"mm")}`)}${this.item("mdi:weather-sunset-up",localized(this.hass,"Sunrise","Napkelte"),this.time(c.sunrise_entity))}${this.item("mdi:weather-sunset-down",localized(this.hass,"Sunset","Napnyugta"),this.time(c.sunset_entity))}${this.item("mdi:blur",localized(this.hass,"Air quality","Levegőminőség"),this.value(c.air_quality_entity))}${this.item("mdi:flower-pollen",localized(this.hass,"Pollen","Pollen"),this.value(c.pollen_entity))}</div>${observed?html`<div class="observed"><ha-icon icon="mdi:clock-check-outline"></ha-icon>${localized(this.hass,"Observation","Megfigyelés")}: ${new Date(String(observed)).toLocaleString(this.hass.locale?.language||"en",{hour:"2-digit",minute:"2-digit"})}</div>`:nothing}</ha-card>`}
}
