import{LitElement,css,html,nothing,type PropertyValues}from"lit";
import{customElement,property,query,state}from"lit/decorators.js";
import{lumaTokens}from"../styles";
import type{HomeAssistant,LovelaceCard}from"../types";
interface Config{type:string;hash:string;name:string;subtitle?:string;icon?:string;cards?:Record<string,unknown>[];max_width?:number}
type ChildCard=HTMLElement&{hass?:HomeAssistant};
@customElement("luma-popup-card")
export class LumaPopupCard extends LitElement implements LovelaceCard{
 @property({attribute:false})hass?:HomeAssistant;@state()private config?:Config;@state()private open=false;@query(".content")private content?:HTMLElement;
 private childCards:ChildCard[]=[];private locationChanged=()=>this.syncLocation();private keyDown=(event:KeyboardEvent)=>{if(this.open&&event.key==="Escape")this.close()};
 static styles=[lumaTokens,css`:host{display:block;height:0;min-height:0}.layer{position:fixed;inset:0;z-index:1000;display:grid;align-items:end;justify-items:center;pointer-events:none;visibility:hidden}.layer.open{pointer-events:auto;visibility:visible}.scrim{position:absolute;inset:0;background:rgba(18,18,24,.42);opacity:0;backdrop-filter:blur(0);transition:opacity .22s ease,backdrop-filter .22s ease}.open .scrim{opacity:1;backdrop-filter:blur(3px)}.sheet{position:relative;display:grid;grid-template-rows:auto minmax(0,1fr);width:min(var(--sheet-width),calc(100vw - 32px));max-height:min(860px,calc(100dvh - 28px));border:1px solid color-mix(in srgb,var(--primary-text-color) 9%,transparent);border-radius:28px 28px 0 0;background:color-mix(in srgb,var(--primary-color) 2%,var(--luma-surface));box-shadow:0 -10px 50px rgba(0,0,0,.2);overflow:hidden;transform:translateY(calc(100% + 32px));opacity:.8;transition:transform .32s cubic-bezier(.2,.8,.2,1),opacity .22s ease}.open .sheet{transform:translateY(0);opacity:1}.handle{position:absolute;top:9px;left:50%;width:34px;height:4px;border-radius:99px;background:color-mix(in srgb,var(--primary-text-color) 24%,transparent);transform:translateX(-50%)}header{display:grid;grid-template-columns:42px minmax(0,1fr) 40px;align-items:center;gap:12px;padding:25px 20px 14px;border-bottom:1px solid color-mix(in srgb,var(--primary-text-color) 6%,transparent)}.icon{display:grid;place-items:center;width:42px;height:42px;border-radius:14px;color:var(--primary-color);background:color-mix(in srgb,var(--primary-color) 12%,transparent)}.icon ha-icon{--mdc-icon-size:22px}.title{font-size:18px;font-weight:730;line-height:1.15}.subtitle{margin-top:3px;color:var(--luma-muted);font-size:11px}.close{display:grid;place-items:center;width:40px;height:40px;padding:0;border:0;border-radius:50%;color:var(--primary-text-color);background:color-mix(in srgb,var(--primary-text-color) 6%,transparent)}.close ha-icon{--mdc-icon-size:19px}.content{display:grid;align-content:start;gap:14px;min-height:160px;padding:16px 20px calc(22px + env(safe-area-inset-bottom));overflow:auto;overscroll-behavior:contain}.loading{display:grid;place-items:center;min-height:160px;color:var(--luma-muted);font-size:12px}@media(min-width:700px){.layer{padding-bottom:18px}.sheet{border-radius:28px;max-height:calc(100dvh - 56px)}}@media(max-width:699px){.sheet{width:100%;max-height:calc(100dvh - 8px);border-right:0;border-bottom:0;border-left:0}.content{padding-right:16px;padding-left:16px}}@media(prefers-reduced-motion:reduce){.scrim,.sheet{transition-duration:.01ms}}`];
 connectedCallback(){super.connectedCallback();window.addEventListener("hashchange",this.locationChanged);window.addEventListener("location-changed",this.locationChanged);window.addEventListener("keydown",this.keyDown);this.syncLocation()}
 disconnectedCallback(){window.removeEventListener("hashchange",this.locationChanged);window.removeEventListener("location-changed",this.locationChanged);window.removeEventListener("keydown",this.keyDown);super.disconnectedCallback()}
 setConfig(c:Config){if(!c?.hash||!c?.name)throw new Error("Luma popup requires hash and name.");this.config={cards:[],max_width:720,...c};this.childCards=[];this.syncLocation()}getCardSize(){return 0}
 protected updated(changed:PropertyValues<this>){if(changed.has("config" as never))void this.mountCards();if(changed.has("hass"))for(const card of this.childCards)card.hass=this.hass}
 private syncLocation(){if(!this.config)return;const expected=this.config.hash.startsWith("#")?this.config.hash:"#"+this.config.hash;this.open=window.location.hash===expected}
 private close(){const oldURL=window.location.href;history.pushState(null,"",window.location.pathname+window.location.search);window.dispatchEvent(new Event("location-changed"));window.dispatchEvent(new HashChangeEvent("hashchange",{oldURL,newURL:window.location.href}))}
 private async mountCards(){if(!this.config||!this.content)return;const helpers=await window.loadCardHelpers?.();if(!helpers)return;this.childCards=(this.config.cards||[]).map(config=>helpers.createCardElement(config)as ChildCard);for(const card of this.childCards){card.hass=this.hass;card.style.width="100%"}this.content.replaceChildren(...this.childCards)}
 render(){if(!this.config)return nothing;return html`<div class=${`layer ${this.open?"open":""}`} aria-hidden=${!this.open}><div class="scrim" @click=${()=>this.close()}></div><section class="sheet" role="dialog" aria-modal="true" aria-label=${this.config.name} style=${`--sheet-width:${this.config.max_width}px`} @click=${(e:Event)=>e.stopPropagation()}><div class="handle"></div><header><span class="icon"><ha-icon icon=${this.config.icon||"mdi:lightning-bolt-outline"}></ha-icon></span><span><div class="title">${this.config.name}</div>${this.config.subtitle?html`<div class="subtitle">${this.config.subtitle}</div>`:nothing}</span><button class="close" aria-label="Bezárás" @click=${()=>this.close()}><ha-icon icon="mdi:close"></ha-icon></button></header><div class="content"><div class="loading">Betöltés…</div></div></section></div>`}
}
