import { LitElement, css, html, nothing, type PropertyValues } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { entityIcon, runAction } from "../helpers";
import { lumaTokens } from "../styles";
import type { HassEntity, HomeAssistant, LovelaceCard, LumaAction } from "../types";

interface WasteItem { entity:string; name:string; icon?:string; color?:string }
interface BaseConfig { type:string; items:WasteItem[] }
interface HeroConfig extends BaseConfig { title?:string; acknowledgement_entity?:string; top_spacing?:number }
interface CollectionConfig extends WasteItem { type:string; tap_action?:LumaAction }
interface AckConfig { type:string; entity:string; confirmation?:string; color?:string }

const daysTo=(e:HassEntity|undefined):number|undefined=>{const n=Number(e?.attributes.daysTo);return Number.isFinite(n)?n:undefined};
const dayLabel=(days:number|undefined):string=>days===undefined?"Nincs adat":days===0?"Ma":days===1?"Holnap":`${days} nap múlva`;
const nextDate=(e:HassEntity|undefined,locale?:string):string=>{const key=Object.keys(e?.attributes||{}).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)).sort()[0];if(!key)return"Dátum nélkül";const d=new Date(`${key}T12:00:00`);return d.toLocaleDateString(locale||"hu-HU",{month:"short",day:"numeric",weekday:"short"})};

@customElement("luma-waste-hero-card")
export class LumaWasteHeroCard extends LitElement implements LovelaceCard{
  @property({attribute:false})hass?:HomeAssistant;@state()private config?:HeroConfig;
  static styles=[lumaTokens,css`
    ha-card{position:relative;min-height:158px;padding:27px;border:1px solid color-mix(in srgb,var(--tone) 19%,transparent);border-radius:var(--luma-radius-hero);background:radial-gradient(circle at 88% 20%,color-mix(in srgb,var(--tone) 18%,transparent),transparent 32%),linear-gradient(135deg,color-mix(in srgb,var(--tone) 14%,var(--luma-surface)),var(--luma-surface) 66%);box-shadow:0 18px 50px rgba(0,0,0,.075);overflow:hidden}.top{display:grid;grid-template-columns:56px minmax(0,1fr) auto;grid-template-areas:"icon title badge" "icon sub badge";align-items:center;gap:4px 16px}.icon{grid-area:icon;display:grid;place-items:center;width:56px;height:56px;border-radius:18px;color:var(--tone);background:color-mix(in srgb,var(--tone) 15%,transparent)}.icon ha-icon{--mdc-icon-size:29px}.title{grid-area:title;align-self:end;font-size:clamp(21px,4vw,27px);font-weight:var(--luma-weight-title);line-height:1.1}.sub{grid-area:sub;align-self:start;color:var(--luma-muted);font-size:12px}.badge{grid-area:badge;padding:7px 11px;border-radius:999px;color:var(--badge-tone);background:color-mix(in srgb,var(--badge-tone) 13%,transparent);font-size:11px;font-weight:720;white-space:nowrap}.rail{display:flex;flex-wrap:wrap;gap:7px;margin-top:18px}.chip{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border-radius:999px;color:var(--item-tone);background:color-mix(in srgb,var(--item-tone) 10%,transparent);font-size:11px;font-weight:680}.chip ha-icon{--mdc-icon-size:15px}@media(max-width:599px){ha-card{min-height:0;padding:19px}.top{grid-template-columns:46px minmax(0,1fr);grid-template-areas:"icon title" "icon sub"}.icon{width:46px;height:46px;border-radius:15px}.icon ha-icon{--mdc-icon-size:24px}.badge{display:none}.rail{margin-top:14px}.chip{flex:1 1 calc(50% - 4px);justify-content:center}}
  `];
  setConfig(c:HeroConfig){if(!c?.items?.length)throw Error("Waste hero requires items.");this.config={title:"Hulladékgyűjtés",...c}}
  getCardSize(){return 3}
  protected shouldUpdate(changed:PropertyValues<this>){if(!changed.has("hass"))return true;const old=changed.get("hass")as HomeAssistant|undefined;return!old||this.config!.items.some(x=>old.states[x.entity]!==this.hass?.states[x.entity])||Boolean(this.config?.acknowledgement_entity&&old.states[this.config.acknowledgement_entity]!==this.hass?.states[this.config.acknowledgement_entity])}
  render(){if(!this.hass||!this.config)return nothing;const entries=this.config.items.map(x=>({...x,days:daysTo(this.hass!.states[x.entity])})),valid=entries.filter(x=>x.days!==undefined),next=valid.length?Math.min(...valid.map(x=>x.days!)):undefined,upcoming=valid.filter(x=>x.days===next),taken=this.config.acknowledgement_entity?this.hass.states[this.config.acknowledgement_entity]?.state==="on":false,urgent=next!==undefined&&next<=2,tone=urgent?"var(--warning-color)":"var(--primary-color)",badgeTone=taken&&urgent?"var(--success-color)":tone;const sub=next===undefined?"A következő gyűjtés nem ismert":`${dayLabel(next)} · ${upcoming.map(x=>x.name).join(" + ")}`;return html`<ha-card style=${`--tone:${tone};--badge-tone:${badgeTone};margin-top:${this.config.top_spacing||0}px`}><div class="top"><span class="icon"><ha-icon icon="mdi:recycle-variant"></ha-icon></span><span class="title">${this.config.title}</span><span class="sub">${sub}</span><span class="badge">${taken&&urgent?"Kihelyezve":urgent?"Hamarosan":"Ütemezve"}</span></div><div class="rail">${entries.map(x=>html`<span class="chip" style=${`--item-tone:${x.color||"var(--primary-color)"}`}><ha-icon icon=${x.icon||entityIcon(this.hass!.states[x.entity],"mdi:trash-can-outline")}></ha-icon>${x.name} · ${dayLabel(x.days)}</span>`)}</div></ha-card>`}
}

@customElement("luma-waste-collection-card")
export class LumaWasteCollectionCard extends LitElement implements LovelaceCard{
  @property({attribute:false})hass?:HomeAssistant;@state()private config?:CollectionConfig;
  static styles=[lumaTokens,css`
    ha-card{display:grid;grid-template-columns:46px minmax(0,1fr) auto;grid-template-areas:"icon name day" "icon date day";align-items:center;gap:3px 12px;min-height:84px;padding:16px;border:1px solid color-mix(in srgb,var(--tone) 13%,transparent);border-radius:var(--luma-radius-card);background:linear-gradient(145deg,color-mix(in srgb,var(--tone) 8%,var(--luma-surface)),var(--luma-surface) 72%);box-shadow:0 12px 32px color-mix(in srgb,var(--tone) 6%,transparent);transition:.17s ease}ha-card:hover{transform:translateY(-2px);border-color:color-mix(in srgb,var(--tone) 24%,transparent);box-shadow:0 16px 38px color-mix(in srgb,var(--tone) 11%,transparent)}.icon{grid-area:icon;display:grid;place-items:center;width:46px;height:46px;border-radius:15px;color:var(--tone);background:color-mix(in srgb,var(--tone) 15%,transparent)}.icon ha-icon{--mdc-icon-size:23px}.name{grid-area:name;align-self:end;font-size:14px;font-weight:700}.date{grid-area:date;align-self:start;color:var(--luma-muted);font-size:10px;text-transform:capitalize}.day{grid-area:day;padding:6px 9px;border-radius:999px;color:var(--tone);background:color-mix(in srgb,var(--tone) 12%,transparent);font-size:11px;font-weight:720;white-space:nowrap}
  `];
  setConfig(c:CollectionConfig){if(!c?.entity||!c?.name)throw Error("Waste collection requires entity and name.");this.config=c}getCardSize(){return 2}
  render(){if(!this.hass||!this.config)return nothing;const e=this.hass.states[this.config.entity],days=daysTo(e),tone=this.config.color||((days??99)<=2?"var(--warning-color)":"var(--primary-color)");return html`<ha-card class="interactive" style=${`--tone:${tone}`} @click=${()=>runAction(this,this.hass!,this.config?.tap_action||{action:"more-info"},this.config?.entity)}><span class="icon"><ha-icon icon=${this.config.icon||entityIcon(e,"mdi:trash-can-outline")}></ha-icon></span><span class="name">${this.config.name}</span><span class="date">${nextDate(e,this.hass.locale?.language)}</span><span class="day">${dayLabel(days)}</span></ha-card>`}
}

@customElement("luma-waste-ack-card")
export class LumaWasteAckCard extends LitElement implements LovelaceCard{
  @property({attribute:false})hass?:HomeAssistant;@state()private config?:AckConfig;@state()private pending=false;private timer?:number;
  static styles=[lumaTokens,css`
    ha-card{display:grid;grid-template-columns:44px minmax(0,1fr) auto;grid-template-areas:"icon name pill" "icon sub pill";align-items:center;gap:3px 12px;min-height:78px;padding:15px 16px;border:1px solid color-mix(in srgb,var(--tone) 15%,transparent);border-radius:var(--luma-radius-card);background:linear-gradient(145deg,color-mix(in srgb,var(--tone) 8%,var(--luma-surface)),var(--luma-surface));box-shadow:0 11px 30px color-mix(in srgb,var(--tone) 6%,transparent)}.icon{grid-area:icon;display:grid;place-items:center;width:44px;height:44px;border-radius:14px;color:var(--tone);background:color-mix(in srgb,var(--tone) 14%,transparent)}.icon ha-icon{--mdc-icon-size:22px}.name{grid-area:name;align-self:end;font-size:14px;font-weight:700}.sub{grid-area:sub;align-self:start;color:var(--luma-muted);font-size:10px}.pill{grid-area:pill;padding:6px 9px;border-radius:999px;color:var(--tone);background:color-mix(in srgb,var(--tone) 12%,transparent);font-size:10px;font-weight:760}.done{cursor:default;opacity:.88}
  `];
  setConfig(c:AckConfig){if(!c?.entity)throw Error("Waste acknowledgement requires entity.");this.config=c}getCardSize(){return 1}
  private activate(){if(!this.hass||!this.config||this.hass.states[this.config.entity]?.state==="on")return;if(!this.pending){this.pending=true;clearTimeout(this.timer);this.timer=window.setTimeout(()=>this.pending=false,3500);return}this.pending=false;void this.hass.callService("input_boolean","turn_on",undefined,{entity_id:this.config.entity})}
  render(){if(!this.hass||!this.config)return nothing;const done=this.hass.states[this.config.entity]?.state==="on",tone=done?"var(--success-color)":this.config.color||"var(--primary-color)";return html`<ha-card class=${done?"done":"interactive"} style=${`--tone:${tone}`} role=${done?"status":"button"} @click=${()=>this.activate()}><span class="icon"><ha-icon icon=${done?"mdi:check-circle-outline":this.pending?"mdi:check":"mdi:trash-can-arrow-up-outline"}></ha-icon></span><span class="name">${done?"Kukák kihelyezve":this.pending?"Biztosan kihelyezted?":"Kihelyezés nyugtázása"}</span><span class="sub">${done?"A következő gyűjtéshez előkészítve":this.pending?(this.config.confirmation||"Koppints újra a nyugtázáshoz"):"Jelöld késznek, amikor kivitted a kukákat"}</span><span class="pill">${done?"KÉSZ":this.pending?"MEGERŐSÍTÉS":"NYUGTÁZÁS"}</span></ha-card>`}
}
