import {LitElement,css,html,nothing,type PropertyValues} from "lit";
import {customElement,property,state} from "lit/decorators.js";
import {entityIcon,entityName,runAction} from "../helpers";
import {lumaTokens} from "../styles";
import type {HomeAssistant,LumaAction,LovelaceCard} from "../types";
interface Config{type:string;entity:string;name?:string;subtitle?:string;icon?:string;color?:string;active_color?:string;active_states?:string[];state_map?:Record<string,string>;decimals?:number;unit?:string;format?:"time";absolute?:boolean;positive_suffix?:string;negative_suffix?:string;secondary_entity?:string;secondary_prefix?:string;secondary_suffix?:string;secondary_decimals?:number;tap_action?:LumaAction}
@customElement("luma-metric-card") export class LumaMetricCard extends LitElement implements LovelaceCard{
 @property({attribute:false})hass?:HomeAssistant;@state()private config?:Config;
 static styles=[lumaTokens,css`.card{display:grid;grid-template-columns:40px minmax(0,1fr);grid-template-areas:"icon label" "icon value" "icon secondary";align-items:center;gap:1px 10px;min-height:72px;padding:13px;border:1px solid var(--luma-border);border-radius:18px;background:linear-gradient(145deg,color-mix(in srgb,var(--tone) var(--mix),var(--luma-surface)),var(--luma-surface));box-shadow:0 10px 28px rgba(0,0,0,.045);transition:.18s ease}.card.interactive:hover{transform:translateY(-2px);box-shadow:0 15px 36px rgba(0,0,0,.08)}.icon{grid-area:icon;display:grid;place-items:center;width:40px;height:40px;border-radius:13px;color:var(--tone);background:color-mix(in srgb,var(--tone) 13%,transparent)}.icon ha-icon{--mdc-icon-size:21px}.label{grid-area:label;align-self:end;color:var(--luma-muted);font-size:9px;font-weight:760;letter-spacing:.05em;text-transform:uppercase}.value{grid-area:value;font-size:20px;font-weight:740;line-height:1.05;white-space:nowrap}.secondary{grid-area:secondary;align-self:start;min-width:0;color:var(--luma-muted);font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}`];
 setConfig(c:Config){if(!c?.entity)throw new Error("Luma metric requires entity.");this.config={active_states:[],...c}}getCardSize(){return 1}
 protected shouldUpdate(changed:PropertyValues<this>){if(!changed.has("hass"))return true;const old=changed.get("hass") as HomeAssistant|undefined;return !old||old.states[this.config!.entity]!==this.hass?.states[this.config!.entity]||Boolean(this.config!.secondary_entity&&old.states[this.config!.secondary_entity]!==this.hass?.states[this.config!.secondary_entity])}
 private format(id:string,decimals?:number,unit?:string,map?:Record<string,string>){const e=this.hass?.states[id];if(!e)return "—";if(map?.[e.state])return map[e.state];if(this.config?.format==="time"){const d=new Date(e.state);return Number.isNaN(d.getTime())?"—":d.toLocaleTimeString(this.hass?.locale?.language||undefined,{hour:"2-digit",minute:"2-digit"})}const n=Number(e.state),shown=this.config?.absolute&&Number.isFinite(n)?Math.abs(n):n;const value=decimals!==undefined&&Number.isFinite(shown)?shown.toFixed(decimals):this.config?.absolute&&Number.isFinite(shown)?String(Math.round(shown)):e.state;const suffix=Number.isFinite(n)?(n>=0?this.config?.positive_suffix:this.config?.negative_suffix):"";return `${value}${unit!==undefined?unit:e.attributes.unit_of_measurement?` ${e.attributes.unit_of_measurement}`:""}${suffix?` ${suffix}`:""}`}
 render(){if(!this.hass||!this.config)return nothing;const e=this.hass.states[this.config.entity],active=this.config.active_states?.includes(e?.state),tone=active?(this.config.active_color||"var(--success-color)"):(this.config.color||"var(--secondary-text-color)"),secondary=this.config.secondary_entity?`${this.config.secondary_prefix||""}${this.format(this.config.secondary_entity,this.config.secondary_decimals,this.config.secondary_suffix||undefined)}`:(this.config.subtitle||"");return html`<ha-card class=${`card ${this.config.tap_action?"interactive":""}`} style=${`--tone:${tone};--mix:${active?"9%":"4%"}`} @click=${()=>runAction(this,this.hass!,this.config?.tap_action,this.config?.entity)}><span class="icon"><ha-icon icon=${this.config.icon||entityIcon(e)}></ha-icon></span><span class="label">${this.config.name||entityName(e,this.config.entity)}</span><span class="value">${this.format(this.config.entity,this.config.decimals,this.config.unit,this.config.state_map)}</span>${secondary?html`<span class="secondary">${secondary}</span>`:nothing}</ha-card>`}}
