import { LitElement, css, html, nothing, type PropertyValues } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { entityIcon, entityName, runAction } from "../helpers";
import { lumaTokens } from "../styles";
import type { HassEntity, HomeAssistant, LovelaceCard, LumaAction } from "../types";

interface Common{exclude?:string[];maximum?:number}
interface HeroConfig extends Common{type:string;title?:string;subtitle?:string;tap_action?:LumaAction;top_spacing?:number}
interface GridConfig extends Common{type:string;name:string;description?:string;icon?:string;minimum?:number;color?:string;empty_text?:string}
const defaults=["sensor.system_power_battery","sensor.battery","sensor.low_battery","binary_sensor.low_battery"];
const candidates=(hass:HomeAssistant,c:Common):Array<{entity:HassEntity;value:number}>=>Object.values(hass.states).flatMap(entity=>{if(entity.entity_id.split(".")[0]!=="sensor")return[];if([...(c.exclude||[]),...defaults].includes(entity.entity_id))return[];const registry=hass.entities?.[entity.entity_id];if(registry?.hidden||registry?.hidden_by||registry?.disabled||registry?.disabled_by)return[];const name=String(entity.attributes.friendly_name||entity.entity_id).toLowerCase(),id=entity.entity_id.toLowerCase(),deviceClass=entity.attributes.device_class,looks=deviceClass==="battery"||id.includes("battery")||id.includes("akku")||name.includes("battery")||name.includes("akku")||/(^|[^a-záéíóöőúüű])elem([^a-záéíóöőúüű]|$)/i.test(name),value=Number(entity.state),unit=entity.attributes.unit_of_measurement;if(!looks||!Number.isFinite(value)||value<0||value>100||!(unit==="%"||unit==="%%"||unit==null))return[];return[{entity,value}] }).sort((a,b)=>a.value-b.value);
const tone=(v:number)=>v<25?"var(--error-color)":v<60?"var(--warning-color)":"var(--success-color)";

@customElement("luma-battery-hero-card")
export class LumaBatteryHeroCard extends LitElement implements LovelaceCard{
 @property({attribute:false})hass?:HomeAssistant;@state()private config?:HeroConfig;
 static styles=[lumaTokens,css`
  ha-card{padding:27px;border:1px solid color-mix(in srgb,var(--tone) 19%,transparent);border-radius:var(--luma-radius-hero);background:radial-gradient(circle at 89% 18%,color-mix(in srgb,var(--tone) 17%,transparent),transparent 31%),linear-gradient(135deg,color-mix(in srgb,var(--tone) 13%,var(--luma-surface)),var(--luma-surface) 66%);box-shadow:0 18px 50px rgba(0,0,0,.075)}.top{display:grid;grid-template-columns:58px minmax(0,1fr) auto;grid-template-areas:"icon title badge" "icon sub badge";align-items:center;gap:4px 17px}.icon{grid-area:icon;display:grid;place-items:center;width:58px;height:58px;border-radius:19px;color:var(--tone);background:color-mix(in srgb,var(--tone) 15%,transparent)}.icon ha-icon{--mdc-icon-size:30px}.title{grid-area:title;align-self:end;font-size:clamp(21px,4vw,27px);font-weight:720;line-height:1.1}.sub{grid-area:sub;align-self:start;color:var(--luma-muted);font-size:12px}.badge{grid-area:badge;padding:7px 11px;border-radius:999px;color:var(--tone);background:color-mix(in srgb,var(--tone) 13%,transparent);font-size:11px;font-weight:720}.stats{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.stat{display:flex;align-items:center;gap:7px;padding:7px 10px;border-radius:999px;background:color-mix(in srgb,var(--primary-text-color) 5%,transparent);font-size:11px;font-weight:680}.stat ha-icon{--mdc-icon-size:16px}@media(max-width:599px){ha-card{padding:19px}.top{grid-template-columns:46px minmax(0,1fr);grid-template-areas:"icon title" "icon sub";gap:3px 12px}.icon{width:46px;height:46px;border-radius:15px}.icon ha-icon{--mdc-icon-size:24px}.badge{display:none}.stats{margin-top:14px}.stat{flex:1;justify-content:center}}
 `];
 setConfig(c:HeroConfig){this.config={title:"Akkumulátorok",subtitle:"Csak a 60% alatti eszközök",maximum:60,...c}}getCardSize(){return 3}
 protected shouldUpdate(changed:PropertyValues<this>){return !changed.has("hass")||changed.get("hass")!==this.hass}
 render(){if(!this.hass||!this.config)return nothing;const all=candidates(this.hass,this.config).filter(x=>x.value<(this.config!.maximum??60)),critical=all.filter(x=>x.value<25).length,watch=all.length-critical,t=critical?"var(--error-color)":watch?"var(--warning-color)":"var(--success-color)";return html`<ha-card class=${this.config.tap_action?"interactive":""} style=${`--tone:${t};margin-top:${this.config.top_spacing||0}px`} @click=${()=>runAction(this,this.hass!,this.config?.tap_action)}><div class="top"><span class="icon"><ha-icon icon="mdi:battery-heart-variant"></ha-icon></span><span class="title">${this.config.title}</span><span class="sub">${this.config.subtitle}</span><span class="badge">${all.length?`${all.length} figyelendő`:"Minden rendben"}</span></div><div class="stats"><span class="stat" style="color:var(--error-color)"><ha-icon icon="mdi:battery-alert"></ha-icon>${critical} kritikus</span><span class="stat" style="color:var(--warning-color)"><ha-icon icon="mdi:battery-50"></ha-icon>${watch} figyelendő</span></div></ha-card>`}
}

@customElement("luma-battery-grid-card")
export class LumaBatteryGridCard extends LitElement implements LovelaceCard{
 @property({attribute:false})hass?:HomeAssistant;@state()private config?:GridConfig;
 static styles=[lumaTokens,css`
  .wrap{display:grid;gap:10px}.head{display:grid;grid-template-columns:31px minmax(0,1fr);align-items:center;gap:10px;padding:7px 2px 4px}.head-icon{display:grid;place-items:center;width:31px;height:31px;border-radius:10px;color:var(--tone);background:color-mix(in srgb,var(--tone) 11%,transparent)}.head-icon ha-icon{--mdc-icon-size:17px}.name{font-size:14px;font-weight:720}.description{margin-top:2px;color:var(--luma-muted);font-size:10px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.item{display:grid;grid-template-columns:42px minmax(0,1fr) auto;grid-template-areas:"icon name value" "icon bar value";align-items:center;gap:5px 11px;min-height:76px;padding:13px;border:1px solid color-mix(in srgb,var(--item-tone) 13%,transparent);border-radius:18px;color:inherit;background:linear-gradient(145deg,color-mix(in srgb,var(--item-tone) 7%,var(--luma-surface)),var(--luma-surface));box-shadow:0 10px 27px color-mix(in srgb,var(--item-tone) 5%,transparent);font:inherit;text-align:left}.icon{grid-area:icon;display:grid;place-items:center;width:42px;height:42px;border-radius:14px;color:var(--item-tone);background:color-mix(in srgb,var(--item-tone) 14%,transparent)}.icon ha-icon{--mdc-icon-size:21px}.item-name{grid-area:name;min-width:0;overflow:hidden;font-size:12px;font-weight:680;text-overflow:ellipsis;white-space:nowrap}.value{grid-area:value;color:var(--item-tone);font-size:13px;font-weight:740}.bar{grid-area:bar;height:5px;border-radius:99px;background:color-mix(in srgb,var(--primary-text-color) 7%,transparent);overflow:hidden}.fill{height:100%;border-radius:inherit;background:var(--item-tone)}.empty{padding:22px;border:1px dashed var(--luma-border);border-radius:18px;color:var(--luma-muted);font-size:12px;text-align:center}@media(max-width:599px){.grid{grid-template-columns:1fr}.item{min-height:72px}}
 `];
 setConfig(c:GridConfig){if(!c?.name)throw Error("Battery grid requires name.");this.config={minimum:0,maximum:60,...c}}getCardSize(){return 3}
 render(){if(!this.hass||!this.config)return nothing;const min=this.config.minimum??0,max=this.config.maximum??60,items=candidates(this.hass,this.config).filter(x=>x.value>=min&&x.value<max),base=this.config.color||"var(--warning-color)";return html`<div class="wrap" style=${`--tone:${base}`}><div class="head"><span class="head-icon"><ha-icon icon=${this.config.icon||"mdi:battery-50"}></ha-icon></span><div><div class="name">${this.config.name}</div>${this.config.description?html`<div class="description">${this.config.description}</div>`:nothing}</div></div>${items.length?html`<div class="grid">${items.map(x=>html`<button class="item interactive" style=${`--item-tone:${tone(x.value)}`} @click=${()=>runAction(this,this.hass!,{action:"more-info"},x.entity.entity_id)}><span class="icon"><ha-icon icon=${entityIcon(x.entity,"mdi:battery-medium")}></ha-icon></span><span class="item-name">${entityName(x.entity,x.entity.entity_id)}</span><span class="value">${Math.round(x.value)}%</span><span class="bar"><span class="fill" style=${`width:${x.value}%`}></span></span></button>`)}</div>`:html`<div class="empty">${this.config.empty_text||"Nincs eszköz ebben a tartományban"}</div>`}</div>`}
}
