import { LitElement, css, html, nothing, type PropertyValues } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { runAction } from "../helpers";
import { lumaTokens } from "../styles";
import type { HomeAssistant, LovelaceCard } from "../types";

interface Config { type:string; weather_entity:string; temperature_entity?:string; humidity_entity?:string; name?:string; back_path?:string }
const labels:Record<string,string>={"clear-night":"Tiszta éjszaka",cloudy:"Felhős",fog:"Köd",hail:"Jégeső",lightning:"Villámlás","lightning-rainy":"Zivatar",partlycloudy:"Részben felhős",pouring:"Szakadó eső",rainy:"Esős",snowy:"Havas","snowy-rainy":"Havas eső",sunny:"Napos",windy:"Szeles","windy-variant":"Szeles",exceptional:"Szélsőséges"};
const icons:Record<string,string>={"clear-night":"mdi:weather-night",cloudy:"mdi:weather-cloudy",fog:"mdi:weather-fog",hail:"mdi:weather-hail",lightning:"mdi:weather-lightning","lightning-rainy":"mdi:weather-lightning-rainy",partlycloudy:"mdi:weather-partly-cloudy",pouring:"mdi:weather-pouring",rainy:"mdi:weather-rainy",snowy:"mdi:weather-snowy","snowy-rainy":"mdi:weather-snowy-rainy",sunny:"mdi:weather-sunny",windy:"mdi:weather-windy","windy-variant":"mdi:weather-windy-variant",exceptional:"mdi:weather-tornado"};

@customElement("luma-weather-hero-card")
export class LumaWeatherHeroCard extends LitElement implements LovelaceCard {
 @property({attribute:false}) hass?:HomeAssistant;@state() private config?:Config;
 static styles=[lumaTokens,css`
  ha-card{position:relative;display:grid;grid-template-columns:auto minmax(0,1fr) auto;grid-template-areas:"back copy weather" "chips chips chips";align-items:center;gap:18px;padding:24px;border:1px solid color-mix(in srgb,var(--tone) 20%,transparent);border-radius:26px;background:radial-gradient(circle at 86% 12%,color-mix(in srgb,var(--tone) 16%,transparent),transparent 34%),linear-gradient(135deg,color-mix(in srgb,var(--tone) 13%,var(--luma-surface)),color-mix(in srgb,var(--tone) 3%,var(--luma-surface)) 64%);box-shadow:0 18px 50px color-mix(in srgb,var(--tone) 9%,transparent)}
  .back{grid-area:back;display:grid;place-items:center;width:54px;height:54px;border:0;border-radius:18px;color:var(--tone);background:color-mix(in srgb,var(--tone) 14%,transparent)}.back ha-icon{--mdc-icon-size:28px}
  .copy{grid-area:copy;min-width:0}.name{font-size:26px;font-weight:740;line-height:1.05}.condition{margin-top:6px;color:var(--luma-muted);font-size:13px}
  .weather{grid-area:weather;display:flex;align-items:center;gap:13px;color:var(--tone)}.weather ha-icon{--mdc-icon-size:48px}.temperature{font-size:36px;font-weight:760;letter-spacing:-.04em}
  .chips{grid-area:chips;display:flex;flex-wrap:wrap;gap:7px;margin-top:2px}.chip{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border-radius:999px;color:var(--primary-text-color);background:color-mix(in srgb,var(--primary-text-color) 6%,transparent);font-size:11px;font-weight:650}.chip ha-icon{--mdc-icon-size:16px;color:var(--tone)}
  @media(max-width:599px){ha-card{grid-template-columns:46px minmax(0,1fr);grid-template-areas:"back copy" "weather weather" "chips chips";gap:12px;padding:18px}.back{width:46px;height:46px;border-radius:15px}.back ha-icon{--mdc-icon-size:24px}.name{font-size:22px}.weather{justify-content:flex-start;padding-left:3px}.weather ha-icon{--mdc-icon-size:40px}.temperature{font-size:32px}.chips{flex-wrap:nowrap;overflow:auto;padding-bottom:2px}.chip{flex:none}}
 `];
 setConfig(c:Config){if(!c?.weather_entity)throw Error("weather_entity required");this.config=c}getCardSize(){return 3}
 protected shouldUpdate(changed:PropertyValues<this>){if(!changed.has("hass"))return true;const old=changed.get("hass")as HomeAssistant|undefined;if(!old)return true;return [this.config?.weather_entity,this.config?.temperature_entity,this.config?.humidity_entity].some(id=>id&&old.states[id]!==this.hass?.states[id])}
 render(){if(!this.hass||!this.config)return nothing;const c=this.config,e=this.hass.states[c.weather_entity],a=e?.attributes||{},state=e?.state||"unavailable",num=(id?:string,attr?:string)=>{const raw=id?this.hass!.states[id]?.state:attr?a[attr]:undefined,n=Number(raw);return Number.isFinite(n)?n:null},temp=num(c.temperature_entity)||num(undefined,"temperature"),humidity=num(c.humidity_entity)||num(undefined,"humidity"),wind=num(undefined,"wind_speed"),apparent=num(undefined,"apparent_temperature"),pressure=num(undefined,"pressure"),tone=["sunny","clear-night"].includes(state)?"#e5a63b":["rainy","pouring","lightning-rainy"].includes(state)?"#5f91ca":["snowy","snowy-rainy","fog"].includes(state)?"#77a8c7":"#6d78c5",chip=(icon:string,label:string)=>html`<span class="chip"><ha-icon icon=${icon}></ha-icon>${label}</span>`;return html`<ha-card style=${`--tone:${tone}`}><button class="back" @click=${()=>c.back_path&&runAction(this,this.hass!,{action:"navigate",navigation_path:c.back_path})}><ha-icon icon=${c.back_path?"mdi:arrow-left":icons[state]||"mdi:weather-cloudy"}></ha-icon></button><div class="copy"><div class="name">${c.name||"Időjárás"}</div><div class="condition">${labels[state]||state}</div></div><div class="weather"><ha-icon icon=${icons[state]||"mdi:weather-cloudy"}></ha-icon><span class="temperature">${temp==null?"—":temp.toFixed(1)+"°"}</span></div><div class="chips">${humidity!=null?chip("mdi:water-percent",`${Math.round(humidity)}% pára`):nothing}${wind!=null?chip("mdi:weather-windy",`${wind} ${a.wind_speed_unit||"km/h"}`):nothing}${apparent!=null?chip("mdi:thermometer-lines",`Hőérzet ${apparent}°`):nothing}${pressure!=null?chip("mdi:gauge",`${Math.round(pressure)} ${a.pressure_unit||"hPa"}`):nothing}</div></ha-card>`}
}
