import { LitElement, css, html, nothing } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { localized, localizedMap } from "../localize";
import { lumaTokens } from "../styles";
import type { HassEntity, HomeAssistant, LovelaceCard } from "../types";

interface Config { type:string; mode_entity:string; power_entity:string; duration_entity:string; start_entity:string; stop_entity:string; ownership_entity:string; boost_active_entity:string; boost_power_entity:string; boost_start_entity:string; boost_cancel_entity:string; boost_error_entity?:string; title?:string }

@customElement("luma-ev-control-card")
export class LumaEvControlCard extends LitElement implements LovelaceCard {
  @property({attribute:false}) hass?:HomeAssistant;
  @state() private config?:Config;
  @state() private pending="";
  @state() private busy="";
  private confirmTimer?:number;
  static styles=[lumaTokens,css`
    ha-card{padding:5px;border:1px solid color-mix(in srgb,var(--primary-color) 13%,transparent);border-radius:22px;background:linear-gradient(145deg,color-mix(in srgb,var(--primary-color) 6%,var(--luma-surface)),var(--luma-surface) 72%);box-shadow:var(--luma-shadow)}.top{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:9px 10px 5px 12px}.title{font-size:14px;font-weight:var(--luma-weight-title)}.mode{display:flex;align-items:center;gap:6px;min-height:30px;padding:6px 11px;border-radius:999px;background:color-mix(in srgb,var(--tone) 10%,transparent);color:var(--tone);font-size:10px;font-weight:700}.mode ha-icon{--mdc-icon-size:15px}
    .page{padding:8px}.status{display:flex;align-items:center;gap:8px;min-height:32px;margin-bottom:8px;padding:7px 10px;border-radius:12px;background:color-mix(in srgb,var(--tone) 8%,transparent);color:var(--tone);font-size:10px;font-weight:680}.status ha-icon{--mdc-icon-size:17px}.status span{color:var(--primary-text-color)}.fields{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.boost-fields{grid-template-columns:minmax(0,1fr)}.field{display:grid;gap:7px;min-width:0;padding:10px;border-radius:15px;background:color-mix(in srgb,var(--primary-text-color) 4%,transparent)}.field-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.field label{overflow:hidden;color:var(--luma-muted);font-size:9px;font-weight:680;text-overflow:ellipsis;white-space:nowrap}.value{font-size:11px;font-weight:720}.field select{width:100%;height:32px;padding:0 9px;border:0;border-radius:10px;background:color-mix(in srgb,var(--primary-text-color) 7%,transparent);color:var(--primary-text-color);font:inherit;font-size:11px}.field input[type=range]{width:100%;height:22px;margin:0;accent-color:var(--primary-color);cursor:pointer}.actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:8px}.single-actions{grid-template-columns:1fr}.active-actions{grid-template-columns:repeat(3,minmax(0,1fr))}.action{display:flex;align-items:center;justify-content:center;gap:8px;min-height:46px;padding:9px 12px;border:1px solid color-mix(in srgb,var(--tone) 16%,transparent);border-radius:15px;background:color-mix(in srgb,var(--tone) 8%,transparent);color:var(--primary-text-color);font:inherit;font-size:11px;font-weight:720;cursor:pointer;transition:.17s ease}.action ha-icon{--mdc-icon-size:19px;color:var(--tone)}.action:hover:not(:disabled){transform:translateY(-1px);background:color-mix(in srgb,var(--tone) 13%,transparent)}.action:disabled{cursor:default;opacity:.42}.action.confirm{--tone:var(--warning-color)}
    @media(max-width:650px){.top{padding:9px 8px 5px}.fields{grid-template-columns:1fr}.actions,.active-actions{grid-template-columns:1fr}}
  `];
  setConfig(config:Config){const required:Array<keyof Config>=["mode_entity","power_entity","duration_entity","start_entity","stop_entity","ownership_entity","boost_active_entity","boost_power_entity","boost_start_entity","boost_cancel_entity"];if(!config||required.some(key=>!config[key]))throw Error("EV control entities required");this.config=config}
  getCardSize(){return 4}
  private entity(id:string):HassEntity|undefined{return this.hass?.states[id]}
  private active(){const state=this.entity(this.config!.ownership_entity)?.state;return Boolean(state&&state!=="unknown"&&state!=="unavailable")}
  private solar(){return this.entity(this.config!.ownership_entity)?.state==="solar"}
  private boost(){return this.entity(this.config!.boost_active_entity)?.state==="on"}
  private option(value:string){return localizedMap(this.hass,{Off:"Off",Solar:"Solar","Charge now":"Charge now"},{Off:"Kikapcsolva",Solar:"Napelemes","Charge now":"Kézi töltés"},value)}
  private async service(domain:string,service:string,entity_id:string,data:Record<string,unknown>={}){if(this.hass)await this.hass.callService(domain,service,data,{entity_id})}
  private async setSelect(entity:string,event:Event){await this.service("select","select_option",entity,{option:(event.target as HTMLSelectElement).value})}
  private async setNumber(entity:string,event:Event){await this.service("number","set_value",entity,{value:Number((event.target as HTMLInputElement).value)})}
  private confirm(key:string,entity:string){if(this.pending!==key){this.pending=key;clearTimeout(this.confirmTimer);this.confirmTimer=window.setTimeout(()=>this.pending="",3200);return}this.pending="";this.busy=key;void this.service("button","press",entity).finally(()=>this.busy="")}
  render(){if(!this.hass||!this.config)return nothing;const active=this.active();return html`<ha-card><div class="top"><span class="title">${this.config.title||localized(this.hass,"Charging control","Töltésvezérlés")}</span><span class="mode" style=${`--tone:${active?"var(--success-color)":"var(--primary-color)"}`}><ha-icon icon=${active?"mdi:ev-plug-type2":"mdi:ev-station"}></ha-icon>${active?localized(this.hass,"Active charging","Aktív töltés"):localized(this.hass,"New session","Új session")}</span></div>${active?this.activePage():this.chargePage()}</ha-card>`}
  private chargePage(){const mode=this.entity(this.config!.mode_entity),power=this.entity(this.config!.power_entity),duration=this.entity(this.config!.duration_entity),options=(mode?.attributes.options as string[]|undefined)||[];return html`<div class="page"><div class="status" style="--tone:var(--primary-color)"><ha-icon icon="mdi:ev-station"></ha-icon><span>${localized(this.hass,"Ready for a new charging session","Új töltési session indítható")}</span></div><div class="fields"><div class="field"><div class="field-head"><label>${localized(this.hass,"Mode","Mód")}</label></div><select @change=${(event:Event)=>this.setSelect(this.config!.mode_entity,event)}>${options.map(item=>html`<option value=${item} ?selected=${item===mode?.state}>${this.option(item)}</option>`)}</select></div>${this.numberField(localized(this.hass,"Power limit","Teljesítménylimit"),this.config!.power_entity,power)}<div class="field"><div class="field-head"><label>${localized(this.hass,"Duration","Időtartam")}</label></div><select @change=${(event:Event)=>this.setSelect(this.config!.duration_entity,event)}>${(((duration?.attributes.options as string[]|undefined)||[])).map(item=>html`<option value=${item} ?selected=${item===duration?.state}>${item}</option>`)}</select></div></div><div class="actions single-actions">${this.action("start",this.config!.start_entity,"mdi:play",localized(this.hass,"Start charging","Töltés indítása"),"var(--success-color)",false)}</div></div>`}
  private activePage(){const power=this.entity(this.config!.boost_power_entity),boost=this.boost(),allowed=this.solar(),error=this.config!.boost_error_entity?this.entity(this.config!.boost_error_entity)?.state:undefined,message=boost?localized(this.hass,"Solar boost is active","A Solar boost aktív"):allowed?localized(this.hass,"Solar session ready for boost","A Solar session boostolható"):localized(this.hass,"Boost is available during an observer-owned Solar session","A boost saját Solar session közben használható");return html`<div class="page"><div class="status" style=${`--tone:${boost?"var(--warning-color)":"var(--success-color)"}`}><ha-icon icon=${boost?"mdi:rocket-launch":"mdi:ev-plug-type2"}></ha-icon><span>${message}${error&&error!=="unknown"?` · ${error}`:""}</span></div><div class="fields boost-fields">${this.numberField(localized(this.hass,"Boost power","Boost teljesítmény"),this.config!.boost_power_entity,power)}</div><div class="actions active-actions">${this.action("boost",this.config!.boost_start_entity,"mdi:rocket-launch",localized(this.hass,"Start boost","Boost indítása"),"var(--warning-color)",!allowed||boost)}${this.action("cancel",this.config!.boost_cancel_entity,"mdi:restore",localized(this.hass,"Return to automatic","Automatikus szabályozás"),"var(--primary-color)",!boost)}${this.action("stop",this.config!.stop_entity,"mdi:stop",localized(this.hass,"Stop charging","Töltés leállítása"),"var(--error-color)",false)}</div></div>`}
  private numberField(label:string,entity:string,state?:HassEntity){const min=Number(state?.attributes.min??0),max=Number(state?.attributes.max??11000),step=Number(state?.attributes.step??100),value=Number(state?.state)||min,unit=String(state?.attributes.unit_of_measurement||"W");return html`<div class="field"><div class="field-head"><label>${label}</label><span class="value">${value.toLocaleString(this.hass?.locale?.language||undefined)} ${unit}</span></div><input type="range" min=${min} max=${max} step=${step} .value=${String(value)} @change=${(event:Event)=>this.setNumber(entity,event)}></div>`}
  private action(key:string,entity:string,icon:string,label:string,tone:string,disabled:boolean){const confirming=this.pending===key;return html`<button class=${`action ${confirming?"confirm":""}`} style=${`--tone:${tone}`} ?disabled=${disabled||this.busy===key} @click=${()=>this.confirm(key,entity)}><ha-icon icon=${this.busy===key?"mdi:loading":confirming?"mdi:check":icon}></ha-icon>${confirming?localized(this.hass,"Tap again to confirm","Koppints újra a megerősítéshez"):label}</button>`}
}
