import{LitElement,css,html,nothing,type PropertyValues}from"lit";import{customElement,property,query,state}from"lit/decorators.js";import{glob}from"../helpers";import{lumaTokens}from"../styles";import type{HomeAssistant,LovelaceCard}from"../types";
interface Config{type:string;integration?:string;domain?:string;entity_pattern?:string;state?:string|string[];state_not?:string|string[];attribute_truthy?:string;device_model?:string;friendly_name_endswith?:string;card_type?:string;columns?:number;tablet_columns?:number;mobile_columns?:number;name_remove?:string[];name_from_device?:boolean;subtitle?:string;icon?:string;color?:string;active_states?:string[];active_color?:string;state_map?:Record<string,string>;tap_action?:Record<string,unknown>;hold_action?:Record<string,unknown>;url_suffix?:{from:string;to:string};empty_card?:Record<string,unknown>}
type Child=HTMLElement&{hass?:HomeAssistant};const listed=(e:string|string[]|undefined,v:string)=>e!==undefined&&(Array.isArray(e)?e:[e]).map(x=>x.toLowerCase()).includes(v.toLowerCase());
@customElement("luma-entity-grid-card")export class LumaEntityGridCard extends LitElement implements LovelaceCard{@property({attribute:false})hass?:HomeAssistant;@state()private config?:Config;@query(".grid")private grid?:HTMLElement;private cards:Child[]=[];private signature="";private token=0;
 static styles=[lumaTokens,css`:host{display:block}.grid{display:grid;grid-template-columns:repeat(var(--desktop),minmax(0,1fr));align-items:start;gap:9px}@media(max-width:1023px){.grid{grid-template-columns:repeat(var(--tablet),minmax(0,1fr))}}@media(max-width:599px){.grid{grid-template-columns:repeat(var(--mobile),minmax(0,1fr))}}`];
 setConfig(c:Config){if(!c?.integration&&!c?.domain&&!c?.entity_pattern)throw Error("integration, domain or entity_pattern required");this.config={card_type:"custom:luma-control-card",columns:2,tablet_columns:1,mobile_columns:1,...c};this.signature=""}getCardSize(){return 3}
 protected updated(changed:PropertyValues<this>){if(changed.has("hass")||changed.has("config" as never))void this.sync()}
 private matchesEntity(id:string){if(!this.hass||!this.config)return false;const c=this.config,e=this.hass.states[id],reg=this.hass.entities?.[id],dev=reg?.device_id?this.hass.devices?.[reg.device_id]:undefined;if(!e)return false;if(c.integration&&reg?.platform!==c.integration)return false;if(c.domain&&id.split('.')[0]!==c.domain)return false;if(c.entity_pattern&&!glob(c.entity_pattern,id))return false;if(c.state!==undefined&&!listed(c.state,e.state))return false;if(c.state_not!==undefined&&listed(c.state_not,e.state))return false;if(c.attribute_truthy&&!e.attributes[c.attribute_truthy])return false;if(c.device_model&&dev?.model!==c.device_model)return false;if(c.friendly_name_endswith&&!String(e.attributes.friendly_name||"").endsWith(c.friendly_name_endswith))return false;return true}
 private childConfig(id:string){const c=this.config!,e=this.hass!.states[id],reg=this.hass!.entities?.[id],dev=reg?.device_id?this.hass!.devices?.[reg.device_id]:undefined;let name=c.name_from_device?dev?.name:String(e.attributes.friendly_name||id);for(const text of c.name_remove||[])name=name?.replace(text,"");let tap=c.tap_action||{action:"more-info"};if(c.url_suffix){const related=id.replace(c.url_suffix.from,c.url_suffix.to);tap={action:"url",url_path:this.hass!.states[related]?.state||""}}return{type:c.card_type,entity:id,name:name?.trim(),subtitle:c.subtitle,icon:c.icon,color:c.color,active_states:c.active_states,active_color:c.active_color,state_map:c.state_map,tap_action:tap,hold_action:c.hold_action||{action:"more-info"}}}
 private async sync(){if(!this.hass||!this.config||!this.grid)return;const ids=Object.keys(this.hass.states).filter(id=>this.matchesEntity(id)).sort(),sig=ids.map(id=>`${id}:${this.hass!.states[id].state}:${String(this.hass!.states[id].attributes[this.config!.attribute_truthy||""])}`).join('|');if(sig===this.signature){for(const card of this.cards)card.hass=this.hass;return}this.signature=sig;const token=++this.token,helpers=await window.loadCardHelpers?.();if(!helpers||token!==this.token)return;const configs=ids.length?ids.map(id=>this.childConfig(id)):this.config.empty_card?[this.config.empty_card]:[];this.cards=configs.map(x=>helpers.createCardElement(x)as Child);for(const card of this.cards)card.hass=this.hass;this.grid.replaceChildren(...this.cards)}
 render(){if(!this.config)return nothing;return html`<div class="grid" style=${`--desktop:${this.config.columns};--tablet:${this.config.tablet_columns};--mobile:${this.config.mobile_columns}`}><span></span></div>`}
}
