import { LitElement, css, html, nothing } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { lumaTokens } from "../styles";
import type { HomeAssistant, LovelaceCard } from "../types";

interface Config {type:string;intake_entity?:string;exhaust_entity?:string;delta_entity?:string;rpm_entity?:string;pwm_entity?:string;failure_entity?:string}
@customElement("luma-rack-cooling-card")
export class LumaRackCoolingCard extends LitElement implements LovelaceCard{
  @property({attribute:false})hass?:HomeAssistant;@state()private config?:Config;
  static styles=[lumaTokens,css`
    ha-card{padding:17px;border:1px solid var(--luma-border);border-radius:20px;background:linear-gradient(145deg,color-mix(in srgb,var(--tone) 6%,var(--luma-surface)),var(--luma-surface));box-shadow:0 12px 32px rgba(0,0,0,.05)}.head,.bar-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.title{font-size:14px;font-weight:720}.badge{padding:4px 8px;border-radius:999px;color:var(--tone);background:color-mix(in srgb,var(--tone) 12%,transparent);font-size:10px;font-weight:680}.hero{display:flex;align-items:center;justify-content:center;gap:16px;padding:18px 0}.fan{display:grid;place-items:center;width:58px;height:58px;border-radius:18px;color:var(--tone);background:color-mix(in srgb,var(--tone) 13%,transparent)}.fan ha-icon{--mdc-icon-size:32px;animation:spin var(--speed) linear infinite}.fan.idle ha-icon{animation:none}.temperature{font-size:31px;font-weight:740;letter-spacing:-.04em}.temperature small{font-size:15px}.label,.bar-head{color:var(--luma-muted);font-size:10px}.metrics{padding:8px 0;border-block:1px solid var(--luma-border)}.row{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:9px;min-height:31px;font-size:11px}.row span:first-child{color:var(--luma-muted)}.dots{border-bottom:1px dotted color-mix(in srgb,var(--primary-text-color) 18%,transparent)}.row strong{font-size:12px}.bar-head{margin-top:12px}.track{height:4px;margin-top:6px;overflow:hidden;border-radius:99px;background:color-mix(in srgb,var(--primary-text-color) 10%,transparent)}.fill{height:100%;border-radius:inherit;background:var(--tone);transition:width .3s ease}@keyframes spin{to{transform:rotate(360deg)}}
  `];
  setConfig(c:Config){this.config={intake_entity:"sensor.rack_fan_controller_rack_intake_temperature",exhaust_entity:"sensor.rack_fan_controller_rack_exhaust_temperature",delta_entity:"sensor.rack_fan_controller_rack_delta_temperature",rpm_entity:"sensor.rack_fan_controller_rack_fan_rpm",pwm_entity:"sensor.rack_fan_controller_rack_fan_commanded_speed",failure_entity:"binary_sensor.rack_fan_controller_rack_fan_failure",...c}}
  getCardSize(){return 5}
  private number(id?:string){const value=Number(this.hass?.states[id||""]?.state);return Number.isFinite(value)?value:undefined}
  render(){if(!this.hass||!this.config)return nothing;const c=this.config,exhaust=this.number(c.exhaust_entity),rpm=this.number(c.rpm_entity)||0,pwm=Math.max(0,Math.min(100,this.number(c.pwm_entity)||0)),failure=this.hass.states[c.failure_entity||""]?.state==="on";let tone="var(--info-color,var(--primary-color))",status="Normál";if(failure){tone="var(--error-color)";status="Ventilátorhiba"}else if(exhaust===undefined){tone="var(--secondary-text-color)";status="Nem elérhető"}else if(exhaust>=42){tone="var(--error-color)";status="Vészhűtés"}else if(exhaust>=38){tone="var(--warning-color)";status="Magas hőmérséklet"}else if(exhaust>=34){status="Aktív hűtés"}const row=(name:string,value:number|undefined,unit:string,decimals=0)=>html`<div class="row"><span>${name}</span><i class="dots"></i><strong>${value===undefined?"—":`${value.toFixed(decimals)} ${unit}`}</strong></div>`;return html`<ha-card style=${`--tone:${tone};--speed:${Math.max(.4,Math.min(3,1000/Math.max(rpm,1)))}s`}><div class="head"><span class="title">Rack hűtés</span><span class="badge">${status}</span></div><div class="hero"><span class=${`fan ${rpm?"":"idle"}`}><ha-icon icon="mdi:fan"></ha-icon></span><div><div class="temperature">${exhaust===undefined?"—":exhaust.toFixed(1)}<small>${exhaust===undefined?"":" °C"}</small></div><div class="label">Kifújt levegő</div></div></div><div class="metrics">${row("Beszívott",this.number(c.intake_entity),"°C",1)}${row("Hőlépcső",this.number(c.delta_entity),"°C",1)}${row("Fordulatszám",rpm,"RPM")}${row("PWM parancs",pwm,"%")}</div><div class="bar-head"><span>${failure?"Ventilátorhiba":pwm>=80?"Nagy teljesítményű hűtés":pwm>=40?"Aktív hűtés":"Automatikus szabályozás"}</span><span>${Math.round(pwm)}%</span></div><div class="track"><div class="fill" style=${`width:${pwm||3}%`}></div></div></ha-card>`}
}
