import{LitElement,css,html,nothing}from"lit";import{customElement,property,state}from"lit/decorators.js";import{lumaTokens}from"../styles";import{entityState,runAction}from"../helpers";import type{HomeAssistant,LovelaceCard,LumaAction}from"../types";
interface Config{type:string;entity:string;remaining_entity?:string;total_entity?:string;name?:string;icon?:string;color?:string;idle_states?:string[];state_map?:Record<string,string>;tap_action?:LumaAction}
const seconds=(raw:unknown):number|undefined=>{if(typeof raw==="number"&&Number.isFinite(raw))return raw;const s=String(raw??"").trim();if(!s||["unknown","unavailable","none"].includes(s.toLowerCase()))return;const iso=s.match(/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/i);if(iso)return +(iso[1]||0)*3600+ +(iso[2]||0)*60+ +(iso[3]||0);const parts=s.split(":").map(Number);if(parts.every(Number.isFinite)){if(parts.length===3)return parts[0]*3600+parts[1]*60+parts[2];if(parts.length===2)return parts[0]*60+parts[1]}const n=Number(s);return Number.isFinite(n)?n:undefined};
const duration=(value:number|undefined)=>value==null?"":value>=3600?`${Math.floor(value/3600)} ó ${Math.ceil(value%3600/60)} p`:`${Math.ceil(value/60)} p`;
@customElement("luma-appliance-card")export class LumaApplianceCard extends LitElement implements LovelaceCard{@property({attribute:false})hass?:HomeAssistant;@state()private config?:Config;
 static styles=[lumaTokens,css`.card{position:relative;display:grid;grid-template-columns:46px minmax(0,1fr) auto;grid-template-areas:"icon copy value" "bar bar bar";align-items:center;gap:10px 13px;min-height:82px;padding:16px 17px;overflow:hidden;border:1px solid color-mix(in srgb,var(--tone) 15%,transparent);border-radius:20px;background:linear-gradient(145deg,color-mix(in srgb,var(--tone) 9%,var(--luma-surface)),var(--luma-surface) 72%);box-shadow:0 12px 34px color-mix(in srgb,var(--tone) 6%,transparent);transition:.18s ease}.card:hover{transform:translateY(-2px)}.icon{grid-area:icon;display:grid;place-items:center;width:46px;height:46px;border-radius:15px;color:var(--tone);background:color-mix(in srgb,var(--tone) 14%,transparent)}.icon ha-icon{--mdc-icon-size:24px}.copy{grid-area:copy;min-width:0}.name{font-size:14px;font-weight:720}.state{margin-top:4px;color:var(--luma-muted);font-size:11px}.value{grid-area:value;color:var(--tone);font-size:12px;font-weight:720;white-space:nowrap}.bar{grid-area:bar;height:7px;border-radius:999px;background:color-mix(in srgb,var(--primary-text-color) 7%,transparent);overflow:hidden}.fill{height:100%;border-radius:inherit;background:linear-gradient(90deg,color-mix(in srgb,var(--tone) 70%,white),var(--tone));transition:width .35s ease}.idle .bar{display:none}@media(max-width:480px){.card{padding:14px}.value{font-size:11px}}`];
 setConfig(c:Config){if(!c?.entity)throw Error("entity required");this.config={idle_states:["off","power_off","idle","complete","completed","unknown","unavailable"],...c}}getCardSize(){return 2}
 render(){if(!this.hass||!this.config)return nothing;const c=this.config,e=this.hass.states[c.entity],state=e?.state||"unavailable",idle=c.idle_states!.includes(state.toLowerCase()),remaining=seconds(c.remaining_entity?this.hass.states[c.remaining_entity]?.state:undefined),total=seconds(c.total_entity?this.hass.states[c.total_entity]?.state:undefined),progress=!idle&&remaining!=null&&total!=null&&total>0?Math.max(0,Math.min(100,(1-remaining/total)*100)):undefined,tone=c.color||(!idle?"var(--info-color,var(--primary-color))":"var(--luma-muted)");return html`<ha-card class=${`card interactive ${idle?"idle":""}`} style=${`--tone:${tone}`} @click=${()=>runAction(this,this.hass!,c.tap_action||{action:"more-info"},c.entity)}><span class="icon"><ha-icon icon=${c.icon||"mdi:washing-machine"}></ha-icon></span><span class="copy"><div class="name">${c.name||String(e?.attributes.friendly_name||c.entity)}</div><div class="state">${entityState(this.hass,e,c.state_map)}</div></span><span class="value">${!idle&&remaining!=null?`${duration(remaining)} van hátra`:idle?"Készenlét":progress!=null?`${Math.round(progress)}%`:"Folyamatban"}</span><span class="bar"><span class="fill" style=${`width:${progress??18}%`}></span></span></ha-card>`}
}
