import { LitElement, css, html, nothing } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { lumaTokens } from "../styles";
import type { HomeAssistant, LovelaceCard } from "../types";
interface Forecast{datetime?:string;condition?:string;temperature?:number;templow?:number;precipitation?:number;precipitation_probability?:number}
interface Config{type:string;weather_entity:string;fallback_entity?:string;days?:number}
const icons:Record<string,string>={"clear-night":"mdi:weather-night",cloudy:"mdi:weather-cloudy",fog:"mdi:weather-fog",hail:"mdi:weather-hail",lightning:"mdi:weather-lightning","lightning-rainy":"mdi:weather-lightning-rainy",partlycloudy:"mdi:weather-partly-cloudy",pouring:"mdi:weather-pouring",rainy:"mdi:weather-rainy",snowy:"mdi:weather-snowy","snowy-rainy":"mdi:weather-snowy-rainy",sunny:"mdi:weather-sunny",windy:"mdi:weather-windy"};
@customElement("luma-weather-forecast-card")
export class LumaWeatherForecastCard extends LitElement implements LovelaceCard{
 @property({attribute:false})private _hass?:HomeAssistant;@state()private config?:Config;@state()private forecast:Forecast[]=[];@state()private loading=true;private fetchedFor="";
 set hass(v:HomeAssistant|undefined){this._hass=v;this.requestUpdate();void this.load()}get hass(){return this._hass}
 static styles=[lumaTokens,css`ha-card{padding:16px;border:1px solid var(--luma-border);border-radius:22px;background:linear-gradient(145deg,color-mix(in srgb,var(--info-color,var(--primary-color)) 6%,var(--luma-surface)),var(--luma-surface));box-shadow:var(--luma-shadow)}.days{display:grid;grid-template-columns:repeat(var(--days),minmax(0,1fr));gap:8px}.day{display:grid;justify-items:center;gap:7px;min-width:0;padding:13px 8px;border-radius:16px;background:color-mix(in srgb,var(--primary-text-color) 4%,transparent)}.date{font-size:10px;font-weight:720;text-transform:capitalize}.icon{color:var(--primary-color);--mdc-icon-size:27px}.temps{font-size:12px;font-weight:720}.low{margin-left:4px;color:var(--luma-muted);font-weight:560}.rain{color:var(--info-color,var(--primary-color));font-size:9px}.loading{display:grid;place-items:center;min-height:104px;color:var(--luma-muted);font-size:12px}@media(max-width:599px){ha-card{padding:12px}.days{display:flex;overflow:auto;gap:7px;scroll-snap-type:x proximity}.day{flex:0 0 104px;scroll-snap-align:start}}`];
 setConfig(c:Config){if(!c?.weather_entity)throw Error("weather_entity required");this.config={days:5,...c};this.fetchedFor="";void this.load()}getCardSize(){return 3}
 private async load(){if(!this._hass||!this.config||this.fetchedFor===this.config.weather_entity)return;this.fetchedFor=this.config.weather_entity;this.loading=true;let items:Forecast[]=[];try{const result=await this._hass.callWS?.<Record<string,unknown>>({type:"call_service",domain:"weather",service:"get_forecasts",service_data:{type:"daily"},target:{entity_id:this.config.weather_entity},return_response:true});const response=(result?.response||result)as Record<string,unknown>,entry=(response?.[this.config.weather_entity]||{})as Record<string,unknown>;items=(entry.forecast||[])as Forecast[]}catch{}if(!items.length&&this.config.fallback_entity){const raw=this._hass.states[this.config.fallback_entity]?.attributes.forecast_data;items=Array.isArray(raw)?raw as Forecast[]:raw&&typeof raw==="object"?[raw as Forecast]:[]}this.forecast=items.slice(0,this.config.days);this.loading=false}
 render(){if(!this.config)return nothing;if(this.loading)return html`<ha-card><div class="loading">Előrejelzés betöltése…</div></ha-card>`;if(!this.forecast.length)return html`<ha-card><div class="loading">Nincs elérhető előrejelzés</div></ha-card>`;const lang=this.hass?.locale?.language||"hu-HU";return html`<ha-card><div class="days" style=${`--days:${this.forecast.length}`}>${this.forecast.map(x=>{const date=x.datetime?new Intl.DateTimeFormat(lang,{weekday:"short"}).format(new Date(x.datetime)):"—",rain=x.precipitation_probability??x.precipitation;return html`<div class="day"><span class="date">${date}</span><ha-icon class="icon" icon=${icons[x.condition||""]||"mdi:weather-cloudy"}></ha-icon><span class="temps">${x.temperature??"—"}°<span class="low">${x.templow!=null?x.templow+"°":""}</span></span>${rain!=null?html`<span class="rain">${rain}% csapadék</span>`:nothing}</div>`})}</div></ha-card>`}
}
